### ISSUE TITLE
Transaction event fires twice

### ISSUE THREAD

**Issue by Pogooo** [ripple/ripple-lib#1001]
When I make a Payment transaction from that account, which subscribed to the transaction event, I get the event about the transaction twice. (in this case the sender is "rayfbat8iqs8GTQ4bqChTdxFcZxGaJaipA")

Here is the subscription code:

```
import * as util from "util";
            (...)
            this.client.connection.on("transaction", (event: TransactionEvent) => {
                console.log(util.inspect(event, {showHidden: false, depth: null}));
            });
            this.client.connection.request({
                command: "subscribe",
                accounts: [ "rayfbat8iqs8GTQ4bqChTdxFcZxGaJaipA" ]
            });
```

**Comment by intelliot** [comment]
That code looks correct. I ran the code and sent a transaction to the account. I only received the event about the transaction once. Perhaps there's a bug elsewhere in your code that makes the subscribe request a second time?

**Comment by Pogooo** [comment]
You are right, sorry for my ticket it was my bad.
