### ISSUE TITLE
Did you forget to publish 1.2.2 to npm?

### ISSUE THREAD

**Issue by alexkvak** [ripple/ripple-lib#1003]
There is new release on github, but there is no new release on NPM.
Could you publish it?
Thanks!

**Comment by intelliot** [comment]
Browser builds were broken in this release; I'll update npm with the next version, which will be fixed to build a browser version properly.

**Comment by intelliot** [comment]
Use [1.2.3](https://github.com/ripple/ripple-lib/releases/tag/1.2.3).
