### ISSUE TITLE
Check Owner Reserve

### ISSUE THREAD

**Issue by cujo30227** [ripple/ripple-lib#1019]
When preparing and signing payments, I sometimes get an UNFUNDED_PAYMENT error, even though I'm checking that the sending account has more than the Base Reserve left.
I figured that this occurs when the sending account also has additional Owner Reserves.

How can I check the total Reserved XRP on an account before initiating a payment?

Thanks!

**Comment by tuloski** [comment]
https://xrpl.org/rippleapi-reference.html#getaccountinfo

You can do "ownerCount*5 + 20" to get the amount of reserved XRP. This won't take into account

**Comment by cujo30227** [comment]
Cool, thanks!
Amazing response time :)

**Comment by tuloski** [comment]
To be completely safe you can also do a: https://xrpl.org/rippleapi-reference.html#getserverinfo

And instead of using hardcoded 5 and 20 you can use validatedLedger.reserveIncrementXRP and validatedLedger.reserveBaseXRP.

**Comment by cujo30227** [comment]
Even better, thanks!
