### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by iPhonePKAndroid** [ripple/ripple-lib#1020]
did you have?

**Comment by intelliot** [comment]
Xpring SDK may have a Python version in the future: https://xpring.io/docs#xrpl

Alternatively, integrating with a REST API is possible in Python and any other language: https://github.com/ripple/xrp-api

**Comment by movitto** [comment]
Here is the ruby client: https://github.com/DevNullProd/XRBP

Perhaps a good starting point for a port
