### ISSUE TITLE
`getLedgerVersion()` may return `null` when processing many payments in parallel

### ISSUE THREAD

**Issue by michbak** [ripple/ripple-lib#1024]
It happens in `preparePayment()` method - it returns `maxLedgerVersion` set to `3`. It is very easy to reproduce. Just try to send about 3 transactions at the same time using `Promise.all()`.

Our software tries to process transactions in parallel - but they are always for different source accounts. So, I guess it should be possible, right?

**Comment by michbak** [comment]
Sorry, my bad. Everything is fine.

**Comment by intelliot** [comment]
No problem. For the benefit of others, what was the issue? 

The default maxLedgerVersionOffset is quite small and makes sense for cases where you want a transaction to quickly succeed or fail. During times when fees are escalating, this is useful for increasing your fee and submitting again.

**Comment by michbak** [comment]
Each transaction promise was checking if there is Ripple connection. If not, each of them was trying to make a connection. But, all of them were using the same ripple-lib instance. I had to make sure they are trying to connect one at a time.

By the way I think it could be handled by the library itself. Or maybe there is already support for such situations?

Anyway my code looks like this:

```
  async makeSureConnected()
    {
    if (!this.theRipple.isConnected())
      {
      if (this.theConnectingPromise)
        {
        await this.theConnectingPromise;
        return;
        }

      this.theConnectingPromise = new Promise((resolve, reject) =>
        {
        TransactionLogger.info('Ripple has to reconnect.');
        this.theRipple.connect()
          .then(() =>
            {
            TransactionLogger.info('Ripple successfully connected.');
            resolve();
            })
          .catch(error =>
            {
            reject(error);
            });
        });

      await this.theConnectingPromise;
      this.theConnectingPromise = null;
      }
    }
```
