### ISSUE TITLE
How do I generate ripple secret from mnemonic seed words ? 

### ISSUE THREAD

**Issue by rahuldamodar94** [ripple/ripple-lib#1025]
How do I generate ripple secret from mnemonic seed words ? 
I am able to generate the public and private key pair. I am also able to do payment. **But how do I retrieve the secret ? I need this secret so that I can import my ripple account to another wallet**. 

const RippleAPI = require('ripple-lib').RippleAPI;
const bip39 = require("bip39");
const bip32 = require("ripple-bip32");
const ripple = require('ripplelib')

var generate = function() {
    mnemonic = bip39.generateMnemonic()

    const seed = bip39.mnemonicToSeed(mnemonic)
    const m = bip32.fromSeedBuffer(seed)
    const keyPair = m.derivePath("m/44'/144'/0'/0/0").keyPair.getKeyPairs()
    const key = ripple.KeyPair.from_json(keyPair.privateKey.substring(2))
    console.log('privateKey: ' + keyPair.privateKey)
    console.log('privateKeyWif: ' + key.to_pri_string()) // to_wif
    console.log('publicKey: ' + keyPair.publicKey)
    console.log('address: ' + key.to_address_string())
}

generate();

**Comment by intelliot** [comment]
If you generated your key pair from mnemonic seed words, you probably do not have a secret. Thus, it is unlikely that you'll be able to import your account to another wallet if that wallet requires a secret. The wallet may need to add support for importing a private key (or mnemonic).

Which wallet is it?

Learn more: https://xrpcommunity.blog/keys-are-key-secret-keys-signing-transactions/

**Comment by rahuldamodar94** [comment]
> If you generated your key pair from mnemonic seed words, you probably do not have a secret. Thus, it is unlikely that you'll be able to import your account to another wallet if that wallet requires a secret. The wallet may need to add support for importing a private key (or mnemonic).
> 
> Which wallet is it?
> 
> Learn more: https://xrpcommunity.blog/keys-are-key-secret-keys-signing-transactions/
I am creating a wallet in which addresses are generated for users using the seed words. So its not possible to get the secret key if i am creating key pairs using mnemonic seed words ?

**Comment by intelliot** [comment]
There is no secret (starting with `s...`), so the wallet that you want to use must have support for importing a private key instead. Which wallet is it?

Alternatively, you can generate a new secret and use it to generate a public key to use as your account's regular key, but then the wallet must have support for regular keys.
