### ISSUE TITLE
Update to the latest version of jsonschema

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1040]
It may be helpful to update to the latest version of jsonschema.

https://github.com/tdegrunt/jsonschema

We were unable to do this in the past due to an incompatibility with our json schemas.

https://github.com/ripple/ripple-lib/issues/880

https://github.com/ripple/ripple-lib/pull/882

https://github.com/tdegrunt/jsonschema/issues/253

This needs to be investigated further.

**Comment by mvadari** [comment]
No longer relevant, we're getting rid of jsonschemas in v2.0
