### ISSUE TITLE
ValidationError(xrpToDrops: value '0.00620165625' has too many decimal places.)

### ISSUE THREAD

**Issue by StarNeit** [ripple/ripple-lib#1043]
When I send XRP from one address to another address, I received this error now.

`ValidationError(xrpToDrops: value '0.00620165625' has too many decimal places.)`

It said that Error was in `preparePayment` and `makeSpend`

Can you please advice how to fix this error? I am just sending 6 XRP, so I can not find out why this happens now.

**Comment by StarNeit** [comment]
I think this error is coming from this line.

https://github.com/ripple/ripple-lib/blob/develop/src/common/utils.ts#L82

But, I can not control this amount because I am just sending 6 xrp using makeSpend function.

**Comment by intelliot** [comment]
@StarNeit What do you mean by "makeSpend"? There is no makeSpend function in ripple-lib.
