### ISSUE TITLE
Document the secp256k1 and Ed25519 private key formats

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1045]
Follow-up to #797 

There may be some existing documentation here, but I think it would help to elaborate and provide some specific examples. We should also document/explain the difference between the key formats used by rippled vs. ripple-lib. Docs should appear at https://xrpl.org/rippleapi-reference.html#sign and/or be linked from there.

/cc @mDuo13

**Comment by mDuo13** [comment]
The [recently updated key derivation docs](https://github.com/ripple/xrpl-dev-portal/pull/704) may be instructive here, but they don't cover any differences in how ripple-lib encodes stuff.

**Comment by intelliot** [comment]
To learn more, start with the aforementioned docs: https://xrpl.org/cryptographic-keys.html
