### ISSUE TITLE
Multiple Payments tefMAX_LEDGER Tentative Message:  Ledger sequence too high.

### ISSUE THREAD

**Issue by issevpar** [ripple/ripple-lib#1047]
I have this error when i try multiple payments. How can I fix. Only one payments SUCCESS but others have failed? Why ? Any Suggestion.

**Comment by intelliot** [comment]
`tefMAX_LEDGER` is a submission error, but it ([currently](https://github.com/ripple/rippled/issues/2847)) does not guarantee that the transaction has permanently failed. You should still check if the transaction succeeded. If it did not succeed, then keep reading:

Normally, this error should be rare. If you see it consistently, can you post the code that you're using to prepare the multiple payments?

Look closely at the account sequence and `LastLedgerSequence` (aka `maxLedgerVersion`) that your transactions are using. Is the `LastLedgerSequence` higher than the sequence number (aka version number) of the last validated ledger?

Try using a higher `LastLedgerSequence` (relative to the current ledger sequence). You can also try increasing the fee.

[Related discussion](https://forum.ripple.com/viewtopic.php?f=2&t=15927#p72419)

**Comment by intelliot** [comment]
I'm closing this, but if the errors persist, feel free to reply or create a new issue.
