### ISSUE TITLE
ripple-lib@1.3.4 has a dependency on https-agent-proxy@2.2.1

### ISSUE THREAD

**Issue by alex75it** [ripple/ripple-lib#1064]
`npm install ripple-lib`         (@1.3.4  latest)
>found 1 high severity vulnerability
>  run `npm audit fix` to fix them, or `npm audit` for details

`npm audit`:

>                                 Manual Review                                  
>             Some vulnerabilities require your attention to resolve     
>          Visit https://go.npm.me/audit-guide for additional guidance    
>  High            Machine-In-The-Middle                                         
>  Package         https-proxy-agent                                             
>  Patched in      >=2.2.3                                                       
>  Dependency of   ripple-lib                                                    
>  Path            ripple-lib > https-proxy-agent

**Comment by FKSRipple** [comment]
Duplicate of #1053, looks like this fix was made a few days ago but our release still hasn't gone out yet. I know we have a few things in flight at the moment  /cc @intelliot to help prioritize

**Comment by FKSRipple** [comment]
Release in v1.4.0
