### ISSUE TITLE
constructor.toString().match() returns null - release

### ISSUE THREAD

**Issue by szymonlesisz** [ripple/ripple-lib#1066]
Since Chrome@78.0.3904.70 and Firefox@70.0 constructor name returns different values than you expected inside ./src/common/browser-hacks `match` and throws runtime error.
I saw that you've already fix it in #869 
Could you please release this fix to public?

More details:

Chrome:
![Screenshot 2019-10-28 at 18 40 42](https://user-images.githubusercontent.com/3435913/67703984-9c1bae00-f9b4-11e9-94bc-49a3d0de61b9.png)

Firefox:
![Screenshot 2019-10-28 at 18 50 17](https://user-images.githubusercontent.com/3435913/67704135-db49ff00-f9b4-11e9-9748-503e87694f3a.png)

Funny is that the whole thing is working on localhost but throws below error on production.
However it works before with Chrome@77.0.3865.120 and start failing after Chrome update.

**Comment by intelliot** [comment]
So this was a breaking change in Chrome 78?

I'll do a release now.

**Comment by intelliot** [comment]
Fixed in 1.4.0

**Comment by szymonlesisz** [comment]
thanks!
