### ISSUE TITLE
Can ensureClassicAddress() allow X address with tag and just ignore the tag？

### ISSUE THREAD

**Issue by yxxyun** [ripple/ripple-lib#1078]
Before send a payment ,my wallet app check the dest address isActivated by call getAccountInfo() and is requireDestinationTag by call getSettings() to remind user send more than 20XRP or force them enter the tag. 

In the ripple-lib@1.4.0 ,when user enter a XAddress  I need decode to ClassicAddress to do these request and then create the payment to the XAddress.

Can ensureClassicAddress() allow X address with tag and just ignore the tag?

**Comment by FKSRipple** [comment]
`ensureClassicAddress()` by the definition of the word needs to "ensure" that an address is "classic" (not an x-address) and fail if it is not. Are you looking for a new method like a "validateClassicAddress" or "convertToClassicAddress" that would handle both types and always return the classic version?

**Comment by yxxyun** [comment]
here 
https://github.com/ripple/ripple-lib/blob/develop/src/ledger/accountinfo.ts#L40
when use with XAddress will need convert to classicAddress first, 
https://github.com/ultiledger/utoken/blob/dev/src/wallet/coins/Ripple.js#L66
but don't need convert to classicAddress when send payment
https://github.com/ultiledger/utoken/blob/dev/src/wallet/coins/Ripple.js#L233

is it possible to direct use getAccountInfo(XAddress)?

**Comment by elmurci** [comment]
@yxxyun closing this issue as it has been inactive for a while. Feel free to create a new issue if the issue persists.
