### ISSUE TITLE
Tests are failing on master branch

### ISSUE THREAD

**Issue by nickewansmith** [ripple/ripple-lib#1091]
On a fresh clone of master I am getting different failing tests each time I run the test suite. I'm using Node 10.0.0. Tests pass with Node 8.10.0

**Comment by FKSRipple** [comment]
We use `develop` as the default branch, and not master. @intelliot can we delete the old `master` branch to remove confusion? Or, something that I've been meaning to ask: is there any reason we can't rename `develop` to `master` to save this confusion, or is that purely for legacy reasons?

You can see our `develop` tests passing on CI here: https://travis-ci.org/ripple/ripple-lib/branches?utm_medium=notification&utm_source=github_status

**Comment by intelliot** [comment]
master is the release branch, ideally it should be passing at all times. If it’s failing then we should do a release which will resolve the issue. I can do a release tomorrow - thanks for surfacing this!

**Comment by FKSRipple** [comment]
oh nice, TIL! Thanks for always remembering to do that!
