### ISSUE TITLE
Test and make use of rippled API versioning

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1105]
https://github.com/ripple/rippled/pull/3155

**Comment by natenichols** [comment]
Do we have a defined way to do rippled api versioning? whats the point of version if theres only one version of rippled API

**Comment by intelliot** [comment]
Yes, if I recall correctly, I think there are now 2 versions in the rippled API (the changes are minor, but there are changes). @mDuo13 are there docs or PRs where we can see exactly what changed? 🙏

**Comment by mvadari** [comment]
Is this the `api_version` param in https://xrpl.org/request-formatting.html? If so, it's being implemented in #1498 (though not tested until we finish the client work).
https://github.com/ripple/ripple-lib/pull/1498/files#diff-03c271e4a4a57be3d3a3af011f81bdbb38ca4272f7ec17e1ef83187d7d9f10afR6

**Comment by cjcobb23** [comment]
There's really only one version right now: https://github.com/ripple/rippled/blob/aee422e8197b9c827587f2a8f009decf1a9f2ac0/src/ripple/rpc/impl/RPCHelpers.h#L224

Version 2 is considered a beta version. You can enable it via the config if you want, but it's not ready for public consumption yet. There might be breaking changes.

**Comment by intelliot** [comment]
@cjcobb23 This is more of a discussion for `rippled` 😃   but my opinion is that we should be liberal with the version numbers: e.g. make `apiVersion: 2` available in rippled 1.7.3, make `apiVersion: 3` available in rippled 1.8.0, make `apiVersion: 4` available in rippled 1.8.1, etc.

Any changes/versions that make it into a stable release should be considered "ready for public consumption". If a client is allowed to specify `apiVersion: 2` when making requests to a stable release of `rippled`, then it should be able to rely on certain known behaviors and response semantics.

**Comment by cjcobb23** [comment]
@intelliot These are valid points. You could make an issue in the rippled repo if you want, so we can discuss there.

I just wanted to let you all know that right now you can't actually test or use anything other than API version 1, unless you have access to a server that has the beta API enabled.

**Comment by mvadari** [comment]
Going to declare this closed because it's been added to request models in #1498. Feel free to reopen if you think further implementation work needs to be done.
