### ISSUE TITLE
Allow connectionTimeout to be customized

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1174]
> It seems like the default value cannot be overwritten because it is not listed on https://github.com/ripple/ripple-lib/blob/develop/src/common/schemas/input/api-options.json

https://github.com/ripple/ripple-lib/pull/1044#issuecomment-574112753

**Comment by southbite** [comment]
forking for now, but yes - this is a bugbear for us as well, we have had to stay on an older version because of this.
