### ISSUE TITLE
Update boilerplate

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1194]
Update:

> RippleAPI is designed to work in Node.js  version 6 or higher. Ripple recommends Node.js v10 LTS.

**Comment by JST5000** [comment]
Seems to be fixed in https://github.com/ripple/ripple-lib/pull/1459

The new wording in the boilerplate to match the readme is: 

> + **[Node.js v14](https://nodejs.org/)** is recommended. Other versions may work but are not frequently tested.

@intelliot Can you confirm if this wording is fine? (Or clarify what wording would be more clear?)

**Comment by intelliot** [comment]
Good point, I think this is fine. In the future we might want to just say that we support the versions currently shown on https://nodejs.org/en/about/releases/ or something like that
