### ISSUE TITLE
Add possibility to load both inbound and outbound transactions

### ISSUE THREAD

**Issue by vanesyan** [ripple/ripple-lib#1216]
Currently `getTransactions` forces us to either to set `initiated` to `false` or `true`, which leads to get only inbound, or outbound transactions. In case if I'd like to get both inbound and outbound transactions in one list (sorted by timestamp) I have to call `getTransactions` 2 times: first with `initiated` set `false` and the second to `true`, then merge two arrays and sort the final array to timestamp. Current way looks odd for me, as we have to do a lot of unnecessary stuffs. As I understand, we already have mixed tx list done right before filtering here https://github.com/ripple/ripple-lib/blob/80b96d9bc92b9e65750bfc40b05a5efc2e9ac97c/src/ledger/transactions.ts#L75

I propose to allow to set `initiated` to `null` in order to get both inbound and outbound transactions in one list.

**Comment by intelliot** [comment]
[`initiated`](https://github.com/ripple/ripple-lib/blob/80b96d9bc92b9e65750bfc40b05a5efc2e9ac97c/src/common/schemas/input/get-transactions.json#L39) should be an optional parameter. If you do not set it, you should get both inbound and outbound transactions.

For `getTransactions`, all of the parameters should be optional except for `address`, which is required.

Does this help?

**Comment by vanesyan** [comment]
Yes. Sorry, I was disturbing you.

**Comment by intelliot** [comment]
No problem - this might be something we can consider clarifying in the docs. Thanks for using ripple-lib! 👍
