### ISSUE TITLE
Use the submit() method to submit a transaction to the network.Appear“Field not found: TransactionType”

### ISSUE THREAD

**Issue by sbihgud** [ripple/ripple-lib#1262]
Hello, there was an error when I was about to submit my signature to the network. My node and ripple lib versions are v12.13.1 and ^ 1.6.5, respectively. Demo and error are also below，

![image](https://user-images.githubusercontent.com/20178448/79446455-d20b2800-8010-11ea-9d52-0adf461963a3.png)

![image](https://user-images.githubusercontent.com/20178448/79446506-e18a7100-8010-11ea-9f41-2179b37f7848.png)

**Comment by hamed-elahifar** [comment]
any news?

**Comment by elmurci** [comment]
can you share your `sign` and `submit` instructions? (remove addresses and secrets from the code).

**Comment by hamed-elahifar** [comment]
all addresses and secrets valid in TEST NET only

`console.clear()
const ripple  = require('ripple-lib')
const api     = new ripple.RippleAPI({server: 'wss://s.altnet.rippletest.net:51233'})

api.connect()

.then(async()=>{

    txJSON = JSON.stringify(doPrepare())

    const response  = api.sign(txJSON, "ssSonmQj2xiyWNymB8UB6169mFDsX")
    const txID      = response.id
    console.log("Identifying hash:", txID)
    const txBlob    = response.signedTransaction
    console.log("Signed blob:", txBlob)

    const earliestLedgerVersion = await doSubmit(txBlob)

    console.log(earliestLedgerVersion)

    api.on('ledger', ledger => {
        console.log("Ledger version", ledger.ledgerVersion, "was validated.")
        // if (ledger.ledgerVersion > maxLedgerVersion) {
        //     console.log("If the transaction hasn't succeeded by now, it's expired")
        // }
    })

    // try {

    //     (async()=>{
    //         tx = await api.getTransaction(txID, {minLedgerVersion: earliestLedgerVersion})
    //         console.log("Transaction result:", tx.outcome.result)
    //         console.log("Balance changes:", JSON.stringify(tx.outcome.balanceChanges))
    //     })()


    // } catch(error) {

    //     console.log("Couldn't get transaction outcome:", error)

    // }

})

async function doPrepare() {

    const preparedTx = await api.prepareTransaction({
        "Account":              "r38VSvqwRHesy6Dk7LBX9VBpwmNixsLT3J",
        "TransactionType":      "Payment",
        "Amount":               api.xrpToDrops("22"),//"2000000",
        "Destination":          "rGCRNJBkqBrYJRyn1GNjHN8YciZoUxXtyh",
        // "Fee":                  12,
        // "Sequence":             2,
    },{
        // Expire this transaction if it doesn't execute within ~5 minutes:
        "maxLedgerVersionOffset": 75
    })
    // const maxLedgerVersion = preparedTx.instructions.maxLedgerVersion
    // console.log("Prepared transaction instructions:", preparedTx.txJSON)
    // console.log("Transaction cost:", preparedTx.instructions.fee, "XRP")
    // console.log("Transaction expires after ledger:", maxLedgerVersion)
    return preparedTx.txJSON

}

async function doSubmit(txBlob) {

    const latestLedgerVersion = await api.getLedgerVersion()

    // const result = await 
    api.submit(txBlob)
    .then(
        // console.log
        )
    .catch(console.log)

    // console.log(result)

    // console.log("Tentative result code:", result.resultCode)
    // console.log("Tentative result message:", result.resultMessage)

    // Return the earliest ledger index this transaction could appear in
    // as a result of this submission, which is the first one after the
    // validated ledger at time of submission.
    return latestLedgerVersion + 1
}`

**Comment by davep-dev** [comment]
Hi, any ideas on this problem?

**Comment by ximinez** [comment]
I'd be interested in seeing the output of those `console.log` calls that are commented out in `doPrepare`. Copied and pasted, not screenshotted, please.

**Comment by elmurci** [comment]
@hamed-elahifar your `doPrepare` is an async function. In your example, you are not "waiting" for it to execute. Adding `await` should remove that error.

**Comment by mvadari** [comment]
Closing this because the original issue-opener hasn't responded in over a year. If you're still having this problem, please reopen the issue.
