### ISSUE TITLE
getTansactions is throwing error error - error [ValidationError(instance.options.maxLedgerVersion is not exactly one from [subschema 0],[subschema 1])]

### ISSUE THREAD

**Issue by webtech2412** [ripple/ripple-lib#1266]
I am facing the same issue, i have set up full node on my server. Everything is working but getTansactions is throwing error error - error [ValidationError(instance.options.maxLedgerVersion is not exactly one from [subschema 0],[subschema 1])]

I tried passing "minLedgerVersion" from my getserverinfo function using the completeLedger values but it is not working and giving MissingLedgerHistoryError(Server is missing ledger history in the specified range)]

I observe completeLedger is giving me random values. I tried to split and use min/max ledger version but that is not working as the format is getting changed
Somitime it give like this
completeLedger ="54873243-54888233,54888334-54888352,54888587-54888604,54888706-54888755,54888921-54888922,54889023-54889061,54889170-54889190,54889347-54889402,54889506-54889562,54889665-54889950,54890141-54890169,54890448-54890460,54890561-54890582,54890694-54890732,54890868-54891060,54891231-54898249"

and some time "completeLedgers": "54873243-54888233,54888334",

How i can resolved this. getTransactions is supposed to work with address only and options are optional but it is not working. Please help.

**Comment by intelliot** [comment]
There are a number of cases where `getTransactions` is difficult to use correctly. Internally, it is primarily an advanced wrapper on [rippled's `account_tx` method](https://xrpl.org/account_tx.html), which I recommend using instead.

You can use ripple-lib to call `account_tx` like so:
```javascript
const result = await api.request('account_tx', { account: 'r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59', ... });
```
Replace `...` with the `account_tx` parameters to use: https://xrpl.org/account_tx.html

To get some of the convenience functionality and formatting 'improvements' provided by `getTransactions`, the best source is the source code:

https://github.com/ripple/ripple-lib/blob/develop/src/ledger/transactions.ts

As for the gaps in your `completeLedgers`, that is a rippled issue. You may have insufficient disk I/O or network bandwidth ([Diagnosing Problems with rippled](https://xrpl.org/diagnosing-problems.html)). If the problem persists, [create an issue for rippled](https://github.com/ripple/rippled/issues/new/choose).

**Comment by webtech2412** [comment]
@intelliot 
Based on your suggestion I have used
const result = await api.request('account_tx',{
                    account: req.body.addr,
                    "binary": false, "ledger_index_max": -1, "ledger_index_min": -1, "limit": 2
                });

Response i get  is 
{ account: 'rUYmt7RWHWjBenRA4uBW2vKJCCtgpTuj3P',
ledger_index_max: 55092767,
ledger_index_min: 55089985,
limit: 2,
transactions: [],
validated: true }

And then I pass min and max to getTransaction API and get below response
[MissingLedgerHistoryError(Server is missing ledger history in the specified range)]

What is the problem here?

**Comment by intelliot** [comment]
1. Why are you calling "getTransaction API"? The response from `api.request('account_tx', ...)` already includes the transactions involving your account.
2. What are the exact options that you're passing to the API? Are you using `minLedgerVersion` / `maxLedgerVersion`?

**Comment by webtech2412** [comment]
Hi @intelliot

**Comment by intelliot** [comment]
Your account (rUYmt7RWHWjBenRA4uBW2vKJCCtgpTuj3P) doesn't have any transactions, so the empty array is correct.

If you're still seeing a problem, please share a snippet of the exact code that you are using.

**Comment by webtech2412** [comment]
Here is my address https://bithomp.com/explorer/**rwuDkywyuMNCcTSRr4HksQCCsfx8g7YMWy**
   It shows I have balance 20.75 and show the transaction on explorer.

 I tried to get the transaction using below code
 "deposit_history": (req, res) => {
        if (!req.body.destTags || !req.body.addr) {
            return commonFile.responseHandler(res, 400, "Parameters missing.")
        }
       
        api.connect().then(async() => {
            try {
                
                const result = await api.request('account_tx',{
                    account: req.body.addr,
                    "binary": false, "ledger_index_max": -1, "ledger_index_min": -1, "limit": 50
                });
                console.log("result is", result.transactions);
            } catch (error) {
                console.log("error", error);
                return commonFile.responseHandler(res, 500, "Internal server error")
            }
        }).then(() => {
            return api.disconnect();
        }).then(() => {
            return commonFile.responseHandler(res, 200, "Txns found successfully.",result.transactions)
        }).catch(error => {
            return commonFile.responseHandler(res, 500, "Error loading Ledger: Txns cannot be found.")
        });

    },

**Response is**
{ account: 'rwuDkywyuMNCcTSRr4HksQCCsfx8g7YMWy',
  ledger_index_max: 55092767,
  ledger_index_min: 55089985,
  limit: 50,
  transactions: [],
  validated: true
 }

Then I try to get balance using below code

"get_addr_info": (req, res) => {
        if (!req.query.addr) {
            return commonFile.responseHandler(res, 400, "Parameters missing.")
        }
        temp = {};
        api.connect().then(() => {
            const myAddress = req.query.addr;
            return api.getAccountInfo(myAddress);
        }).then(info => {
            temp = info
        }).then(() => {
            return api.disconnect();
        }).then(() => {
            return commonFile.responseHandler(res, 200, "Info Found Successfully", temp)
        }).catch((err) => {
console.log("error",err);
            return commonFile.responseHandler(res, 500, "Internal server error.")
        });
    },

**Response is** 
error [RippledError(InsufficientNetworkMode, { error: 'noNetwork',
  error_code: 17,
  error_message: 'InsufficientNetworkMode',
  id: 1788,
  request:
   { account: 'rwuDkywyuMNCcTSRr4HksQCCsfx8g7YMWy',
     command: 'account_info',
     id: 1788,
     ledger_index: 'validated' },
  status: 'error',
  type: 'response' })]

**Comment by elmurci** [comment]
@webtech2412 I tried to execute your code and seems to work as expected. Is this issue still happening?

```
[
  {
    meta: {
      AffectedNodes: [Array],
      DeliveredAmount: '15000000',
      TransactionIndex: 18,
      TransactionResult: 'tesSUCCESS',
      delivered_amount: '15000000'
    },
    tx: {
      Account: 'r9gHv9M6onooNre8w8DWEfAhhMzARs8wuQ',
      Destination: 'rPLCnDVaSmUQhg5Hz9ZsMvyA4ioC2qpiwz',
      DestinationTag: 2035397819,
      Fee: '5000000',
      Flags: 2147483648,
      LastLedgerSequence: 62113097,
      Sequence: 62112763,
      SigningPubKey: '022774A204F664FB6312947AF40C2B29882330C4CA4AC77341FA04B57EA615CEAC',
      TransactionType: 'AccountDelete',
      TxnSignature: '3045022100EAF9D0B082135A07051FDC9B9A15197EA8420D0F8A22D0C3E49766C23CEA2B440220041CF8918F4455C91CA787B56396666A2D655FA8951452286C438CA6D9AEEDB9',
      date: 668703451,
      hash: '6FF03FF338964206E1610A3411F06CCFD119BD9031C2B6CE2E46E053B4015891',
      inLedger: 62113078,
      ledger_index: 62113078
    },
    validated: true
  },
  {
    meta: {
      AffectedNodes: [Array],
      TransactionIndex: 46,
      TransactionResult: 'tesSUCCESS',
      delivered_amount: '4995000'
    },
    tx: {
      Account: 'r9gHv9M6onooNre8w8DWEfAhhMzARs8wuQ',
      Amount: '4995000',
      Destination: 'rPLCnDVaSmUQhg5Hz9ZsMvyA4ioC2qpiwz',
      DestinationTag: 2035397819,
      Fee: '5000',
      Flags: 2147483648,
      LastLedgerSequence: 62112874,
      Sequence: 62112762,
      SigningPubKey: '022774A204F664FB6312947AF40C2B29882330C4CA4AC77341FA04B57EA615CEAC',
      TransactionType: 'Payment',
      TxnSignature: '304402202CB21C3CE8DF6D6DA4894F7181CEFA01C0767409BE721C2FD738556489AB173502203BA18441546427BF0B70B1F5364A8273A3BD5F2D94CBCCAE1BB29FB99D0DA7D0',
      date: 668702590,
      hash: '80D9538A3784999C32F6E037329423A69E9AF26BECAD8B61AE41B014F06A6090',
      inLedger: 62112855,
      ledger_index: 62112855
    },
    validated: true
  },
  {
    meta: {
      AffectedNodes: [Array],
      TransactionIndex: 47,
      TransactionResult: 'tesSUCCESS',
      delivered_amount: '25000000'
    },
    tx: {
      Account: 'rPLCnDVaSmUQhg5Hz9ZsMvyA4ioC2qpiwz',
      Amount: '25000000',
      Destination: 'r9gHv9M6onooNre8w8DWEfAhhMzARs8wuQ',
      Fee: '12',
      Flags: 2147483648,
      LastLedgerSequence: 62112765,
      Sequence: 44,
      SigningPubKey: '035C6A0368001E8820DB8DC6B3D69AB18C17DCEB7FFB62887ED14A824FCBE7A12F',
      TransactionType: 'Payment',
      TxnSignature: '3045022100B60177400411A5CA0F5FAB673A1A415BE3BCCB0B95D557D142C8587DC8BCBA18022052FCDA555385FCD85B3F66AA517A7DA42BDF7E16BE7FBF6497C01230C0929572',
      date: 668702222,
      hash: '8629018820D4419893C4EEB99A5E37110F0EAF33AD42E4592DACB325359E9ED3',
      inLedger: 62112762,
      ledger_index: 62112762
    },
    validated: true
  }
]
```

**Comment by ledhed2222** [comment]
close due to lack of info
