### ISSUE TITLE
[NotConnectedError(certificate has expired, { Error: certificate has expired

### ISSUE THREAD

**Issue by OliverRedmanCooke** [ripple/ripple-lib#1277]
I am currently using the Testnet server to issue transactions for my web app. It looks like the certificate for this domain has expired, can you please renew it. 

Url: https://s.altnet.rippletest.net:51234/

![image](https://user-images.githubusercontent.com/45919110/80702050-5a410100-8ad8-11ea-9377-11878ae6de23.png)

**Comment by intelliot** [comment]
This has been fixed. Thanks for reporting this issue!

**Comment by OliverRedmanCooke** [comment]
Thanks for the quick response!
