### ISSUE TITLE
Unexpected high fee (Version: 1.5.0)

### ISSUE THREAD

**Issue by abcdefg-hijklmnop** [ripple/ripple-lib#1297]
Issue Description:
The API "fee" command, sometimes return a weird answer.
In the response structure, under "drops", there is a field named "open_ledger_fee". Its value in most cases is 10 as expected, but sometimes we are getting high values like 5125, 510$
This is a temporary answer, and If I call within a second or two, I get again the expected 10. So, I can't understand the logic of getting this high fee of more than 5000.

Steps to Reproduce:
Called "fee" API in loop for 100 times in a row.

![ripple-high-fee-bug](https://user-images.githubusercontent.com/51439443/83969206-54a8b900-a8d7-11ea-8cf2-07c5fb838aab.png)

**Comment by abcdefg-hijklmnop** [comment]
Moved the issue from ripple-lib to ripple-d

**Comment by intelliot** [comment]
Depending on your use case, it is usually sufficient to use the `base_fee` plus the minimal additional cost if you're sending a multi-signed tx or an EscrowFinish with a preimage.

You may need to pay the higher fees only if you find that your txs are not getting validated quickly enough for your use case.

https://xrpl.org/transaction-cost.html#reference-transaction-cost
