### ISSUE TITLE
Transaction's public key is not authorized.

### ISSUE THREAD

**Issue by jc0803kevin** [ripple/ripple-lib#1299]
rpc domain  ：https://testnet.data.api.ripple.com

`{
	"result": {
		"broadcast": false,
		"account_sequence_available": 8216999,
		"applied": false,
		"open_ledger_cost": "10",
		"tx_json": {
			"Account": "rH4HXaVJUSjTrkv7ZYwr1mknMZdLc2EkNM",
			"Destination": "rU5eGrf4sZhUmtH3JoYQNUNZqcds59qGsi",
			"TransactionType": "Payment",
			"TxnSignature": "3045022100D333DB07F784ED42C8A7D986E1D1C3C0F201C8C67E838FE075824D2DE28685B00220457131763FC68503FD1CD7C788F9A4D63389BF66FFCB8C017AF7BB368D87B31B",
			"SigningPubKey": "03DD8D18244CF421F57B1D3913D86279FB72F63869A7188334984332ACF8C49CF6",
			"Amount": "10000",
			"Fee": "10",
			"Flags": 2147483648,
			"Sequence": 8216999,
			"DestinationTag": 123456,
			"LastLedgerSequence": 82367344,
			"hash": "15E812F37472800975A8ACFD0157D0EA1B4E664669D6D3122F2C47C808FE1B79"
		},
		"queued": false,
		"engine_result_code": -196,
		"accepted": true,
		"kept": true,
		"validated_ledger_index": 8236733,
		"tx_blob": "120000228000000024007D61A72E0001E240201B04E8D37061400000000000271068400000000000000A732103DD8D18244CF421F57B1D3913D86279FB72F63869A7188334984332ACF8C49CF674473045022100D333DB07F784ED42C8A7D986E1D1C3C0F201C8C67E838FE075824D2DE28685B00220457131763FC68503FD1CD7C788F9A4D63389BF66FFCB8C017AF7BB368D87B31B8114B3888978BCAEA72C11F7CAB1C85CB87062F60D3C831480898A3E40C63CCCE2956A9E120F92BB859E68CC",
		"engine_result": "tefBAD_AUTH",
		"account_sequence_next": 8216999,
		"engine_result_message": "Transaction's public key is not authorized.",
		"status": "success"
	}
}`

withdraw hash ->15E812F37472800975A8ACFD0157D0EA1B4E664669D6D3122F2C47C808FE1B79

Please help to answer, thank you

**Comment by ximinez** [comment]
It looks like you signed the transaction with the wrong secret key.

For example, say there are two accounts:
* `secret1` is the secret for `account1`
* `secret2` is the secret for `account2`
If you have a transaction for `"Account" : "account1"`, and use `secret2` to sign this, you will get this error.

You can confirm this by using the `SigningPubKey` from your transaction as the parameter to `account_info`. Whether the account exists or not, it will give you the corresponding account ID. In this case, you can see they don't match. From the command line:
```
$ rippled account_info 03DD8D18244CF421F57B1D3913D86279FB72F63869A7188334984332ACF8C49CF6
{
   "result" : {
      "account" : "rHqcWyzY16h1LuXLtDod9C6nopVPUCFZrn",
      [...]
      "request" : {
         "account" : "03DD8D18244CF421F57B1D3913D86279FB72F63869A7188334984332ACF8C49CF6",
         "api_version" : 1,
         "command" : "account_info"
      },
      [...]
   }
}
```
The account returned here: `rHqcWyzY16h1LuXLtDod9C6nopVPUCFZrn` is not the same account used in your transaction: `rH4HXaVJUSjTrkv7ZYwr1mknMZdLc2EkNM`.


I'm going to go ahead and close this ticket. If you have any more information or questions, feel free to re-open it, or open a new issue.

**Comment by intelliot** [comment]
@jc0803kevin Where did you get the `testnet.data.api.ripple.com` domain/URL from? That's an old instance of the Testnet Data API and it is no longer functional. Ledgers/data are not being updated since the ETLs no longer work.

**Comment by jc0803kevin** [comment]
@intelliot 这个地址（testnet.data.api.ripple.com）是通过网络获取到的，
本次签名的密钥，是采用hd wallet 推导出来的，为十六进制的字符串，使用以前的 com.ripple:ripple-core:1.0.0 sdk进行离线签名，com.ripple.core.types.known.tx.Transaction#sign(secret)，
希望能看得懂我描述得问题

**Comment by intelliot** [comment]
I am not familiar with an SDK by that name. Are you using ripple-lib?

For Testnet, you can use the URL on this page to connect to a Ripple-hosted Testnet server: https://xrpl.org/xrp-testnet-faucet.html

You can also run rippled yourself and connect it to Testnet.

In any case, do not use testnet.data.api.ripple.com.

**Comment by elmurci** [comment]
@jc0803kevin closing this issue as it has been inactive for a while. Feel free to create a new issue if the issue persists.
