### ISSUE TITLE
Problem with fetching transactions history for specific address with multiple query params

### ISSUE THREAD

**Issue by EnoRage** [ripple/ripple-lib#1309]
Hi! I am from TrustWallet team. We are using ripple api to show transactions for users. We are having some difficulties with it:

1. 
not working
https://data.ripple.com/v2/accounts/rawbonesfckvLGGgDvtGHRXHXrp9quqnpd/transactions?descending=true&limit=25&type=Payment

descending=true
limit=25
type=Payment

<img width="1248" alt="Screenshot 2020-08-12 at 18 06 03" src="https://user-images.githubusercontent.com/22479658/90031937-7dc63b00-dcc6-11ea-9fea-bb9d1ab6f0f4.png">

2.
working
https://data.ripple.com/v2/accounts/rawbonesfckvLGGgDvtGHRXHXrp9quqnpd/transactions?descending=true&limit=25

descending=true
limit=25

<img width="1788" alt="Screenshot 2020-08-12 at 18 06 17" src="https://user-images.githubusercontent.com/22479658/90031979-874fa300-dcc6-11ea-9b38-c1f80f5ce833.png">

3. 
working
https://data.ripple.com/v2/accounts/rawbonesfckvLGGgDvtGHRXHXrp9quqnpd/transactions?limit=25&type=Payment

limit=25
type=Payment

<img width="1324" alt="Screenshot 2020-08-12 at 18 06 48" src="https://user-images.githubusercontent.com/22479658/90032027-99c9dc80-dcc6-11ea-8f7a-5febfa3d46c5.png">

**Comment by intelliot** [comment]
You appear to be using the Data API, which is not related to this repository.

As the Data API currently does not have any uptime/reliability guarantees, I would recommend instead retrieving the transactions from your own [rippled server](https://xrpl.org/manage-the-rippled-server.html).

If you want to use JavaScript/TypeScript, you can use [RippleAPI (ripple-lib)](https://xrpl.org/rippleapi-reference.html) to connect to your rippled server and retrieve transactions.

**Comment by EnoRage** [comment]
Thanks @intelliot
