### ISSUE TITLE
Please return to including a pre-built and minified javascript file for browser compatibility.

### ISSUE THREAD

**Issue by SimpleXRPTools** [ripple/ripple-lib#1310]
I'm not sure if there is enough demand to justify the work, but it would be great if Ripple could go back to including the pre-built and minified javascript file in all future releases.

It allows people to verify that the  **ripple-??.??.??-min.js**  file that I include in my project is coming from the official source. If there's no minified file, there's nothing to check it against.

**Comment by intelliot** [comment]
Thank you for this request, I think it's a good one. The fact that you've opened this issue is good evidence that there is some demand, to help justify the work.

**Comment by intelliot** [comment]
This is done as of version 1.8.1 https://github.com/ripple/ripple-lib/releases
