### ISSUE TITLE
prepareTrustline ripplingDisabled is unuseful

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/ripple-lib#1317]
const trustline = {

        "currency": cname,
        "counterparty": issuer,
        "limit": "10000000000",
        "ripplingDisabled": false,
        "memos": [
            {
                "type": "test",
                "format": "text/plain",
                "data": "texted data"
            }
        ]
    };

i set ripplingDisabled =false,but did not work.when i got trustline,ripplingDisabled still show  true

**Comment by RobertEmmettJones** [comment]
robertemmettjonesjones@gmail.com

**Comment by RobertEmmettJones** [comment]
Robert Emmett Jones assign

**Comment by RobertEmmettJones** [comment]
https://github.com/ripple/ripple-lib/issues/1317#issuecomment-716976024

**Comment by maybeTomorrow** [comment]
ripplingDisabled does'nt change

**Comment by mrosendin** [comment]
I've noticed this too. 

As a workaround, I ensure the account's [Settings](https://xrpl.org/rippleapi-reference.html#settings) has `defaultRipple: true` before creating a trust line.
