### ISSUE TITLE
path_dry!Path could not send partial amount

### ISSUE THREAD

**Issue by maybeTomorrow** [ripple/ripple-lib#1318]
{ resultCode: 'tecPATH_DRY',
  resultMessage: 'Path could not send partial amount.',
  engine_result: 'tecPATH_DRY',
  engine_result_code: 128,
  engine_result_message: 'Path could not send partial amount.',
  tx_blob: '1200002280000000240000D357201B0000E3EF61D56386099B1BF0000000000000000000000000004D4D45000000000092F62C3415807EC90E64068D3C07539529586A6F68400000000000000069D56386099B1BF0000000000000000000000000004D4D45000000000092F62C3415807EC90E64068D3C07539529586A6F7321027FD9306D1D9C630ACD0194F95811341D8557090066AB72B96D28EFDE9B3EB77C74473045022100A176E85C69D09885EA4A62B613F7BC32278C3CC9FB33A2AAC35D92921FA543B502200B434810594BA790A275575169D215F9621707A5CF5D2DE1C36D00B302A74ED38114587F232BA081FDD7788D8595DBABF927FC72495583142282EACF8176C25F04774646DF156DCD440D9372',
  tx_json: 
   { Account: 'r9hvmYQKa1XNi26rdxCLYCdsdDjLcHqRgH',
     Amount: 
      { currency: 'MME',
        issuer: 'rNQhZPHRyQxdFkqttg1MW2Gid2T6G374EM',
        value: '9999' },
     Destination: 'rh97oFpPoc8MFZh1owdKdWBXMdD2n72Fw9',
     Fee: '0',
     Flags: 2147483648,
     LastLedgerSequence: 58351,
     SendMax: 
      { currency: 'MME',
        issuer: 'rNQhZPHRyQxdFkqttg1MW2Gid2T6G374EM',
        value: '9999' },
     Sequence: 54103,
     SigningPubKey: '027FD9306D1D9C630ACD0194F95811341D8557090066AB72B96D28EFDE9B3EB77C',
     TransactionType: 'Payment',
     TxnSignature: '3045022100A176E85C69D09885EA4A62B613F7BC32278C3CC9FB33A2AAC35D92921FA543B502200B434810594BA790A275575169D215F9621707A5CF5D2DE1C36D00B302A74ED3',
     hash: '940B6644CB275C32B7690B9364E361D2D87CE8116428A9F746B87F0BBFCC6F5F' } }

A ->(trust) C (trust) <- B, A transfer to B

**Comment by elmurci** [comment]
@maybeTomorrow I guess this was Testnet as the addresses seem to have been removed (probably by a reset of the Network). Any chance you can provide another example so I can have a look? Thanks!

**Comment by ledhed2222** [comment]
closing because it's stale - @maybeTomorrow please re-open if you have more info
