### ISSUE TITLE
MissingLedgerHistoryError

### ISSUE THREAD

**Issue by adelineu** [ripple/ripple-lib#1322]
At the moment if I try to request the details of a transaction that doesn't exist on the ledger (on **s1.ripple.com**) I get this error:
`MissingLedgerHistoryError: Server is missing ledger history in the specified range` 

The actual error is (on **s2.ripple.com**) and it should be:
`NotFoundError: Transaction not found`

The reason why this happens on **s1** is because this server no longer has the "first ledger" which is pre-set [here](https://github.com/ripple/ripple-lib/blob/f5196389e8554d1653cbfaaa398b0180442888de/src/ledger/utils.ts#L108).

The problem is that if you handle specific errors this behaviour can create unexpected effects.

Solutions:
- don't validate the ledger range if the **transaction** method is called without minLedgerVersion & maxLedgerVersion

**Comment by intelliot** [comment]
@adelineu if the rippled server doesn't have full history, and you don't specify minLedgerVersion & maxLedgerVersion, then there is no way to know that the transaction doesn't exist in the ledger history.

If, when using s1.ripple.com, you got "NotFoundError: Transaction not found", that could be dangerous/misleading. You might think that this means that the transaction was not validated. But in reality, the transaction might have been validated in an older ledger that s1.ripple.com does not have stored.

The recommended solution is to specify minLedgerVersion & maxLedgerVersion, where minLedgerVersion is the earliest ledger that the transaction could appear in, and maxLedgerVersion is the latest (usually the same as LastLedgerSequence).

Does that make sense?

**Comment by adelineu** [comment]
From my experience you're most likely to verify recent transaction (confirm one you just sent - as an example).

So it might make sense to validate for the minimum, but i don't know if does for the maximum, because you're most likely to use only one node to get the latest version and that would be always true (?) (unless it gets the latest version faster and the actual sync isn't as fast).

My problem was that it has a default behaviour, with a pre-set minimum (that might not exist) that ends up being validated, resulting in an unexpected error.

Thank you.
