### ISSUE TITLE
ValidationError: instance.id does not match pattern ripple

### ISSUE THREAD

**Issue by Yeppman** [ripple/ripple-lib#1343]
I'm setting up a function that calls and receives any payments made then I run into this error as I begin

```
const RippleAPI = require('ripple-lib').RippleAPI;

const api = new RippleAPI({
  server: 'wss://s1.ripple.com' // Public rippled server hosted by Ripple, Inc.
});
api.on('error', (errorCode, errorMessage) => {
  console.log(errorCode + ': ' + errorMessage);
});
api.on('connected', () => {
  console.log('connected');
});
api.on('disconnected', (code) => {
  console.log('disconnected, code:', code);
});
api.connect().then(() => {
  /* insert code here */

  
    let checks = 0
    let checktx = setInterval(() => {
        if (checks < 900 ){
            api.getLedgerVersion().then((ledger) => {
                api.getTransaction(addr, {minLedgerVersion:ledger}).then((txs) => {
                    console.log(txs)
                })
            })
            checks++
        } else {
            clearInterval(checktx)
            console.log('Payment is cancelled')
            io.emit({msg: 'Payment is cancelled'})
        }
    }, 1000)

}).then(() => {
  return api.disconnect();
}).catch(console.error);
```

**Comment by elmurci** [comment]
what is the value of `addr`?

**Comment by Yeppman** [comment]
I fixed it, silly mistake, it's getTransactions() not getTransaction() 

The code emit real time payments on your address

Incase any one need this, now I have to find the same solution for ethereum

**Comment by Yeppman** [comment]
`const express = require('express')
const app = express()
const http = require('http').Server(app)
const io = require('socket.io')(http)
const addr = 'rppm2hDuKZVhN1GZ8E3E9syuaTFne53cL6'
const server = 'wss://s.altnet.rippletest.net:51233'

const RippleAPI = require('ripple-lib').RippleAPI
const api = new RippleAPI({server:server})

api.on('error', (code, msg) => {
    console.log(code, msg)
})

api.on('connected', ()=> {
    console.log('connected to testnet');
})

api.on('disconnected', (code)=> {
    console.log('disconnected to testnet');
})

api.connect().then((result) => {
    
    let checks = 0
    let checktx = setInterval(() => {
        if (checks < 900 ){
            api.getLedgerVersion().then((ledger) => {
                api.getTransactions(addr, {minLedgerVersion:ledger}).then((txs) => {
                    console.log(txs)
                    for (tx of txs) {
                        if(tx.specification.destination.tag === 41){
                            clearInterval(checktx)
                            io.emit('emit', {
                                id: elem.id,
                                from: elem.specification.destination.source.address,
                                tag:  elem.specification.destination.source.tag,
                                amount: elem.specification.destination.amount.value,
                                msg: 'payment was recievd'
                            })
                        }
                    }
                })
            })
            checks++
        } else {
            clearInterval(checktx)
            console.log('Payment is cancelled')
            io.emit({msg: 'Payment is cancelled'})
        }
    }, 1000)

}).catch((err) => {
    console.log(err);    
});
`

**Comment by elmurci** [comment]
Are you happy to close this issue @Yeppman?

**Comment by Yeppman** [comment]
> Are you happy to close this issue @Yeppman?

yes
