### ISSUE TITLE
docs are confusing for maxLedgerVersion field of prepare methods

### ISSUE THREAD

**Issue by mDuo13** [ripple/ripple-lib#1344]
See: [transaction instructions](https://xrpl.org/rippleapi-reference.html#transaction-instructions) as well as return value tables for prepare* methods.

- There are two instances of `maxLedgerVersion` with the same description; one is int or null, the other is str or null. There should probably be either one entry that supports all three types, or three separate entries with one type each.
- The description says it could be `one of the following strings: 'validated', 'closed', 'current'.` This is a very weird idea when preparing transactions. By definition, the `validated` ledger is final so the new transaction couldn't possibly apply to any ledger (unless it was valid for a different network fork). The `closed` ledger is also a very unlikely candidate for including new transactions, though at least theoretically it could be possible depending on other servers' timing for beginning consensus on a given ledger index. And `current` is not as crazy but still a probably inadvisable value (same as setting maxLedgerVersionOffset to 0, I think). So it's weird to accept any of those values here.

**Comment by intelliot** [comment]
This will become obsolete if/when jsonschemas are removed in ripple-lib/xrpl.js 2.0
