### ISSUE TITLE
Deno module support

### ISSUE THREAD

**Issue by mrosendin** [ripple/ripple-lib#1345]
Requesting support for [Deno](https://deno.land/x). There are workarounds, but it would be nice to have this supported.

**Comment by mrosendin** [comment]
For anyone using Deno, here's an example of a workaround:

```node
import ripple from 'https://dev.jspm.io/npm:ripple-lib';

(async () => {
  const api = new (ripple as any).RippleAPI({ server: 'wss://s.altnet.rippletest.net:51233' });
  const address = 'rH8NxV12EuV9er1eS34ZhcvVkhfJ5uw9kT';

  api.connect().then(() => {
    api.getBalances(address).then((balances: any) => {
      console.log(JSON.stringify(balances, null, 2));
    });
  });
})();
```

I'm newish to TypeScript and Deno so there might be a better way to do this. I simply tried constructing `RippleAPI` like `new ripple.RippleAPI()` but I got this error:

```
Property 'RippleAPI' does not exist on type '{}'
```

My best guess as to what's going on is that the compiler seems to expect a type for `ripple` because it's imported as a variable. I tried importing RippleAPI like so, but ran into this error:

```node
import { RippleAPI } from 'https://dev.jspm.io/npm:ripple-lib';
```

```
Module '"../../../../Library/Caches/deno/deps/https/dev.jspm.io/a78c92b0c97f76c4ed6e61e378467ae3fd740a2a3af6378ba8475ebab06b8161"' has no exported member 'RippleAPI'. Did you mean to use 'import RippleAPI from "../../../../Library/Caches/deno/deps/https/dev.jspm.io/a78c92b0c97f76c4ed6e61e378467ae3fd740a2a3af6378ba8475ebab06b8161"' instead?
```

**Comment by elmurci** [comment]
@mrosendin I tried to execute your code and worked as expected:

```
[
  {
    "currency": "XRP",
    "value": "4673.999388"
  }
]
```

is this still an issue?

**Comment by mrosendin** [comment]
Hi @elmurci,

I am using [Deno](https://deno.land/) and this issue was a request to add `ripple-lib` support. The code snippet I posted above is a workaround.

Since `ripple-lib` uses node APIs it can't easily be ported to Deno (similar to the problem with using `ripple-lib` in a React Native project). For example, [Denoify](https://github.com/garronej/denoify) can help achieve what [rn-nodeify](https://github.com/tradle/rn-nodeify) does.

The code snippet I posted above is a workaround. I'll close out this issue, but thought it would be helpful to anyone who was also working with Deno and may be helpful if Ripple supports an official Deno port in the future.

**Comment by elmurci** [comment]
Makes sense Matt, I am not very familiar with Deno but will reopen and do some research on how to add Deno support.

**Comment by intelliot** [comment]
The [workaround is in the README](https://github.com/ripple/ripple-lib/#using-ripple-lib-with-deno) and it's the way forward for now. If you have a specific change that would make this library work better with Deno, please open a PR -- we'd love to merge it!
