### ISSUE TITLE
How can I assign Destination Tag to ripple account.

### ISSUE THREAD

**Issue by block-hac** [ripple/ripple-lib#1350]
I am working on small exchange platform.
I want to create one ripple account and then assign one address ( but it has different DESTINATION TAG) for each user.
I use ripple-lib API and I create account .
Now, I need to assign ripple address for every user like follows:
**user1**
```
address : rsRRZzRR3cTUwt9MVycCmkNKqT2vEHAvy2
destination_tag : 418648567 
```
**user2**
```
address : rsRRZzRR3cTUwt9MVycCmkNKqT2vEHAvy2
destination_tag : 418648568
```
**user3**
```
address : rsRRZzRR3cTUwt9MVycCmkNKqT2vEHAvy2
destination_tag : 418648569 
```
...
How can I do this ?
Firstly, I can't find feature to set destination tag to ripple account.
***Please, help me !!!***

**Comment by tuloski** [comment]
You can't set destination tag to a ripple account.
Destination tag is only one parameter you can assign in payment transactions.
The interpretation of destination tag is delegated to 3rd party users usually.

**Comment by block-hac** [comment]
I created Ripple account ( it doesn't contain _destination_tag_ ).
Then, if other person send  XRP to my address with any _destination_tag_, I can check  _detination_tag_ from transaction info.
That's right  ?

**Comment by intelliot** [comment]
Yes, that's right.

If you would like to embed a destination tag into the address, you can use the X-address format. For example, using [ripple-address-codec](https://github.com/ripple/ripple-address-codec):

```
> const api = require('ripple-address-codec')
> api.classicAddressToXAddress('rGWrZyQqhTp9Xu7G5Pkayo7bXjH4k4QYpf', 4294967295)
'XVLhHMPHU98es4dbozjVtdWzVrDjtV18pX8yuPT7y4xaEHi'
```
In this example, `4294967295` is the tag. Apps that support X-addresses can unpack `XVLhHMPHU98es4dbozjVtdWzVrDjtV18pX8yuPT7y4xaEHi`, resulting in `rGWrZyQqhTp9Xu7G5Pkayo7bXjH4k4QYpf` and `4294967295`.

**Comment by mDuo13** [comment]
Looks like this question was answered. Feel free to re-open if you need to know more.
