### ISSUE TITLE
Cannot connect to testner public ripple server

### ISSUE THREAD

**Issue by davidkralprofinit** [ripple/ripple-lib#1381]
Hello, I am using ripple-lib version 1.9.1.

I am connecting to public testnet server wss://s.altnet.rippletest.net as stated in this documentation: https://xrpl.org/get-started-with-rippleapi-for-javascript.html

When I am using Mainnet servers everything is OK. But when I am using testnet wss://s.altnet.rippletest.net/ according to https://xrpl.org/get-started-with-the-rippled-api.html I get following error:

[NotConnectedError(connect ECONNREFUSED 34.210.87.206:443, { Error: connect ECONNREFUSED 34.210.87.206:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '34.210.87.206',
  port: 443 })]

**Comment by intelliot** [comment]
That Testnet server is currently down. Please try the other Testnet server: `server: 'ws://35.158.96.209:51233'`

**Comment by mDuo13** [comment]
**Both servers are back up now, so you can access them the normal way.**

But, for next time:

Sorry, you can't reach 35.158.96.209 by IP from the general internet. (It's accessible if you're on a Ripple VPN). You _can_ reach it from the general internet if you query it by hostname. You could temporarily edit your machine's `/etc/hosts` file to point at one of them specifically:

```
35.158.96.209 s.altnet.rippletest.net
```

Alternatively, you could [connect your own server to the testnet](https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html).
