### ISSUE TITLE
 hello, your project is missing scripts / http.js file

### ISSUE THREAD

**Issue by hungleee99** [ripple/ripple-lib#1383]
please . let share for me .thanks

**Comment by intelliot** [comment]
That file was removed long ago, and no longer works anyway. If you want to view the file, you can see it in the commit history here: https://github.com/ripple/ripple-lib/blob/ba8fe1f32cf7a0ffb068364aeb0fadc34860612d/scripts/http.js

I see that package.json currently references this file in the `start` script. I'll remove that.
