### ISSUE TITLE
Rename generateXAddress to wallet.create

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1388]
Improve consistency with the rippled API: https://xrpl.org/wallet_propose.html

If generateXAddress is the better format, then we should update the rippled API to better match it. Or, we could come up with a combination of the two, and apply changes to both. Either way, it should be relatively consistent across rippled vs ripple-lib, to minimize the learning curve for new users.

I feel that generateXAddress is badly named anyway, since you're not just generating an address, but an object which contains a key pair and an address.

**Comment by intelliot** [comment]
Of course, this should be introduced as non-breaking change by just adding a new method and leaving the existing ones alone. The existing ones can be deprecated and removed in a year or two after the new method is released.

**Comment by intelliot** [comment]
We can add a wallet.create method like xrpl-py https://xrpl-py.readthedocs.io/en/stable/source/xrpl.wallet.html

**Comment by natenichols** [comment]
Closing in favor of #1485
