### ISSUE TITLE
Calculation in getFee sometimes returns NaN when using public (s1, s2) ripple servers

### ISSUE THREAD

**Issue by LynchEntrostat** [ripple/ripple-lib#1398]
Hello, I have recently been experiencing an issue where the `getFee` returns NaN when calling `preparePayment` using Ripple s1 and s2 public servers as the server for the Ripple api. This is because sometimes they do not return the `load_factor` in the response to the request `server_info`. 

I queried the **rippled** library about this and this is their response as to why sometimes `load_factor` is missing. [Reason why load_factor is missing](https://github.com/ripple/rippled/issues/3812#issuecomment-816871100).

Is there any way to default `load_factor` to 1 if it is not defined in the `server_info` request?

**Comment by ximinez** [comment]
This is the same issue as https://github.com/ripple/rippled/issues/3812. I'm going to close this issue. Please move any discussion to the linked issue.

**Comment by intelliot** [comment]
Let's keep this issue open for now, I think we could/should apply a patch to ripple-lib to make it more robust against this 'bug' in rippled reporting mode

**Comment by intelliot** [comment]
Related: https://github.com/XRPLF/xrpl4j/issues/85

**Comment by nkramer44** [comment]
@intelliot They are slightly related, but xrpl4j gets fees via the `fee` RPC method, so this shouldn't be an issue.

**Comment by CherryDT** [comment]
Hi, is there an ETA when this will be included in a release? It seems the latest release is still from April. I already tried `npm install git://github.com/ripple/ripple-lib.git#c8b00358979687477b57a8e65242a1ee2e86d49f` but that doesn't seem to work (probably there are some build steps required).

**Comment by intelliot** [comment]
@CherryDT Thanks for the request! We've released ripple-lib 1.9.5 which includes this fix.
