### ISSUE TITLE
API to provide a function to return 'now'

### ISSUE THREAD

**Issue by lathanbritz** [ripple/ripple-lib#1407]
This is one of the most useful things when developing. Having a way to get the current time with out thinking.

**Problem**
At the moment one has to do some fancy foot work to get the now time stamp for example https://runkit.com/intelliot/ripple-epoch-example https://runkit.com/intelliot/ripple-epoch-example this is prone to developer induced bugs.

**Solution**
Add a method/function to get return the time of the Ripple Epoch. My suggestion would be to extend [iso8601ToRippleTime](https://xrpl.org/rippleapi-reference.html#iso8601torippletime) and allow its use as follows `api.iso8601ToRippleTime('now') `

**Comment by lathanbritz** [comment]
better title

**Comment by mvadari** [comment]
You can get the current time in Ripple Epoch via `api.iso8601ToRippleTime(Date())` or `unixToRippleTimestamp(Date.now())`. This doesn't seem very complicated to do for the developer, so it's not really necessary to add the extra functionality.
