### ISSUE TITLE
Typescript definitions do not resolve properly

### ISSUE THREAD

**Issue by nixer89** [ripple/ripple-lib#1433]
With the current TS-definitions of ripple-lib (v.1.9.5) and using typescript (I tested with version 3.6, 3.9 and 4.2.x) there are various problems defining objects and accessing fields, especially for objects with a property which holds an "Amount" field.

As example, looking at the current amounts.d.ts file, it looks as follows:
![grafik](https://user-images.githubusercontent.com/25486793/121140910-ae212c00-c83a-11eb-9df0-f57880341836.png)

The JSON based interfaces have their properties delimited by an ";" (semicolon) instead of "," (comma). 

When using the ripple-lib TS definitions, various problems arise, as example:

![grafik](https://user-images.githubusercontent.com/25486793/121142061-e5dca380-c83b-11eb-9dc9-fcbe766d4984.png)
(not able to access the amount properties of a payment)

![grafik](https://user-images.githubusercontent.com/25486793/121142169-03aa0880-c83c-11eb-9b76-59c5dc5a4ddc.png)
(not able to access the amount property of an OfferLedgerEntry to retrieve the TakerGets and TakerPays amount values)

and so on.

By manually changing (locally) the delimiters from ";" to "," in the typescript declarion file,  the problem was fixed.

**Comment by florent-uzio** [comment]
Hi @nixer89, thank you for raising this ticket.

You can easily access the properties you need by using `Type Guards` and more specifically the `in` operator:
https://basarat.gitbook.io/typescript/type-system/typeguard#in

You can check the existence of a property like this:
```
if("amount" in payment.source){
// do something with the amount property
}
```

As an example, with this Payment object:

```
let payment: Payment = {
  source: {
    address: "asd",
    amount: {
      value: "50",
      currency: "XRP",
      issuer: "alice",
      counterparty: "eric",
    },
    maxAmount: {
      currency: "XRP",
      value: "60",
    },
  },
  destination: {
    address: "asd",
    amount: {
      value: "45",
      currency: "XRP",
      issuer: "bob",
      counterparty: "john",
    },
    minAmount: {
      currency: "XRP",
      value: "40",
    },
  },
};
```

I created a custom function that prints the `amount` and/or `minAmount` and/or `maxAmount` of the object we pass in:

```
const printAllAmounts = (
  obj: Adjustment | MaxAdjustment | MinAdjustment
): void => {
  if ("amount" in obj) {
    console.log(`The amount is ${obj.amount.value}`);
  }

  if ("minAmount" in obj) {
    console.log(`The minAmount is ${obj.minAmount.value}`);
  }

  if ("maxAmount" in obj) {
    console.log(`The maxAmount  is ${obj.maxAmount.value}`);
  }
};
```

If you run `printAllAmounts(payment.source);`, you will see the `amount` and `maxAmount`.
If you run `printAllAmounts(payment.destination);`, you will see the `amount` and `minAmount`.

![image](https://user-images.githubusercontent.com/36513774/121875122-ada4fb80-cd3a-11eb-84cb-15bbd4ba40f8.png)

By using Type Guards, you can then have access to all the properties of an object:

![image](https://user-images.githubusercontent.com/36513774/121875188-c1e8f880-cd3a-11eb-9eb4-03fbfc172e5a.png)

![image](https://user-images.githubusercontent.com/36513774/121875220-cc0af700-cd3a-11eb-86d5-c74d6bf17c42.png)

Please let me know if you need more clarifications.

**Comment by nixer89** [comment]
Thank you for the clarification!

To be honest, I was not aware of the "Type Guard" feature of Typescript, even though I am working with TS for quite some time already. I never came across this feature before and just didn't know it exists. (So I guess it's not heavily used) . Maybe there could be some hint at an easy to find spot of the docs/readme.

**Comment by florent-uzio** [comment]
Hi @nixer89 , I'm glad it helped.
I will work internally to make our docs/readme more explicit.
We will close this issue. Feel free to create another one if you need it.
Have a good day.
