### ISSUE TITLE
AccountSet: ClearFlag is not part of FormattedSettings

### ISSUE THREAD

**Issue by florent-uzio** [ripple/ripple-lib#1438]
`FormattedSettings` object only includes the following fields:

```
export declare type FormattedSettings = {
    defaultRipple?: boolean;
    depositAuth?: boolean;
    disableMasterKey?: boolean;
    disallowIncomingXRP?: boolean;
    domain?: string;
    emailHash?: string | null;
    walletLocator?: string | null;
    enableTransactionIDTracking?: boolean;
    globalFreeze?: boolean;
    memos?: Memo[];
    messageKey?: string;
    noFreeze?: boolean;
    passwordSpent?: boolean;
    regularKey?: string;
    requireAuthorization?: boolean;
    requireDestinationTag?: boolean;
    signers?: Signers;
    transferRate?: number | null;
    tickSize?: number;
};
```

If I am not wrong, there is no possibility to set `ClearFlag` to remove an Account Flag.

**Comment by intelliot** [comment]
@florent-uzio If you set a setting to `false`, doesn't that set `ClearFlag` behind the scenes?

I didn't verify, but that's what I would expect. For example, set `{defaultRipple: false}`.

**Comment by florent-uzio** [comment]
@intelliot good idea! I will try to test that. I will update this ticket once done.

**Comment by florent-uzio** [comment]
@intelliot if you set a flag to `false` it will indeed set ClearFlag behind the scenes.

I deployed a new version including the `ClearFlag` field in dev and prod.
https://dev.txnbuilder.xrpl.xpring.dev/
