### ISSUE TITLE
Increase LastLedgerSequence in Prepare function

### ISSUE THREAD

**Issue by florent-uzio** [ripple/ripple-lib#1449]
Currently, the `Prepare` function, for a Payment, for example, gives only 3 ledger sequences higher than the current ledger sequence.

Example:
Current Leger `Sequence: 10`
ripple-lib prepares the transaction with `LastLedgerSequence: 13`

In my experience, this value is too small. It would be better to return `+10` (or higher).

The transaction often ends up having the status `tfMAX_LEDGER` and is not submitted to the ledger.

**Comment by intelliot** [comment]
For transactions signed manually, you usually want to omit LastLedgerSequence entirely (or set it to a high value, like 400 which is about 30 minutes).

For transactions signed by an automated process, it's a trade-off. Using 3 allows you know the transaction's final result very quickly (in less than 15 seconds). Using 10 would mean that you may need to wait about 40 seconds before you know that a transaction failed to be processed.

I would be fine with setting the default to 10, but it is important to note that this is a value which the user should often set explicitly (depending on their use case and how long they are willing to wait).

@ledhed2222 @mvadari @mayurbhandary @natenichols thoughts?

**Comment by florent-uzio** [comment]
Thanks @intelliot I actually set the `LastLedgerSequence` field to `required` in https://dev.txnbuilder.xrpl.xpring.dev/
So the user should then avoid seeing `tfMAX_LEDGER` when they submit the transaction.

We might not need to set the default to 10 in ripple-lib for now...

**Comment by intelliot** [comment]
`maxLedgerVersionOffset` might be more user-friendly than `LastLedgerSequence` since it saves the user from having to do the math (taking the current ledger sequence and adding a number to it).

**Comment by florent-uzio** [comment]
Oh great, I didn't know that! I will definitely implement that, thanks

**Comment by florent-uzio** [comment]
@intelliot, I included `maxLedgerVersionOffset` in the UI, it's much easier indeed, thanks for the tip!
I think I can close this issue now.

https://dev.txnbuilder.xrpl.xpring.dev/
https://prod.txnbuilder.xrpl.xpring.dev/
