### ISSUE TITLE
Add convenience method for calling the XRP Faucets

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1484]
https://xrpl.org/xrp-testnet-faucet.html

**Comment by florent-uzio** [comment]
Taking this one

**Comment by intelliot** [comment]
Consider having the function signature be similar to what xrpl-py has: https://xrpl-py.readthedocs.io/en/stable/source/xrpl.asyncio.wallet.html?highlight=testnet#xrpl.asyncio.wallet.generate_faucet_wallet

**Comment by florent-uzio** [comment]
@intelliot would it make sense to have a function like that instead: `generateFaucetWallet(onTesnet: boolean = true)`

By default it will create a faucet wallet on the testnet and if `false` then on the devnet.

That way the user doesn't have to go to xrpl.org to find the Testnet URL, which is easier for him.

**Comment by mvadari** [comment]
@florent-uzio the xrpl-py `generate_faucet_wallet` function determines whether the client is on the testnet or devnet from the client's URL, the user does not need to know the faucet's URL. The user will need to know the testnet URL to do anything on the testnet anyways.
