### ISSUE TITLE
MSB3411 error during npm install

### ISSUE THREAD

**Issue by ThePiachu** [ripple/ripple-lib#216]
When I tried installing the lib with

npm install ripple-lib

I got an error MSB3411 (https://github.com/rwaldron/johnny-five/issues/145). A fix for this problem is to use a command:

npm install ripple-lib --msvs_version=2012

It might be worthwhile to put a note next to the installation instructions about this solution perhaps?

**Comment by wltsmrz** [comment]
One of our developers was unable to get the install to work with this flag. Windows is an entirely untested environment. We should probably add a note somewhere about this, if there isn't a note already. Thanks
