### ISSUE TITLE
Signing with regular key using rsign.js

### ISSUE THREAD

**Issue by lukapusic** [ripple/ripple-lib#243]
I receive the following error when I try to sign a transaction using rsign.js and a regular key instead of the master secret key. Am I doing something wrong, or is signing with the regular key broken? Is this related to a recent fix of #190 and changes to rsign.js?

[Error: Too many loops looking for KeyPair yielding *address* from *secret*

**Comment by sublimator** [comment]
I think a patch fixing the situation would likely be accepted

**Comment by ripplerm** [comment]
a fix suggestion: https://github.com/ripple/ripple-lib/pull/306
