### ISSUE TITLE
Memos Broken

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-lib#250]
People using ripple-lib to recalculate transaction tree hashes have been out of luck.

Seems like the memo json parser is [broken](https://github.com/ripple/ripple-lib/commit/1704ac4ae144c0ce54afad86f644c75a632080b1), and is misinterpreting rippled's hex as if it were utf8.  i.e. `FF` as two bytes, rather than one.

**Comment by geertweening** [comment]
fixed in https://github.com/ripple/ripple-lib/pull/277

**Comment by geertweening** [comment]
https://github.com/ripple/ripple-lib/pull/277 has been merged
