### ISSUE TITLE
_handleResponseSubscribe issue

### ISSUE THREAD

**Issue by vhpoet** [ripple/ripple-lib#256]
As discussed with @wltsmrz 

![screenshot 2015-01-14 16 40 38](https://cloud.githubusercontent.com/assets/686185/5750889/dea126ea-9c0f-11e4-8130-3f16b1c20923.png)

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7774494-_handleresponsesubscribe-issue?utm_campaign=plugin&utm_content=tracker%2F323756&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323756&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by wltsmrz** [comment]
https://github.com/ripple/ripple-lib/pull/257

**Comment by wltsmrz** [comment]
There may also be a problem with .reconnect(). To be investigated later
