### ISSUE TITLE
Error not handled

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#284]
I usually have this kind of error when using Ripple-lib:

events.js:72
        throw er; // Unhandled 'error' event
              ^
RippleError: Unexpected response from remote

90% of the times, it happens when submitting a transaction and the fees are too high for my maximum, so it reports a "tejMaxFeeExceeded". But sometimes it happened with "tejMaxLedger".

**Comment by wltsmrz** [comment]
Do you have the full stack trace? Are you submitting the transaction without a callback by chance?

**Comment by tuloski** [comment]
This is all I have:
{"result":"tejMaxFeeExceeded","result_message":"Error","engine_result":"tejMaxFeeExceeded","engine_result_message":"Error","message":"Error"}

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transaction.EventEmitter.emit (events.js:74:15)
    at Transaction.<anonymous> (/home/tulo/node_modules/ripple-lib/src/js/ripple/transactionmanager.js:198:19)
    at Transaction.g (events.js:180:16)
    at Transaction.EventEmitter.emit (events.js:117:20)
    at TransactionManager._request (/home/tulo/node_modules/ripple-lib/src/js/ripple/transactionmanager.js:657:6)
    at resubmitTransaction (/home/tulo/node_modules/ripple-lib/src/js/ripple/transactionmanager.js:469:10)
    at iterate (/home/tulo/node_modules/ripple-lib/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/tulo/node_modules/ripple-lib/node_modules/async/lib/async.js:165:9)
    at /home/tulo/node_modules/ripple-lib/src/js/ripple/transactionmanager.js:473:11


This is how I submit the offer (with callback):
var transaction = remote.createTransaction('OfferCreate', {
                account: MY_ADD,
                taker_pays: TAKER_PAYS,
                taker_gets: TAKER_GETS,
                cancel_sequence: SEQ
            });
            
    
            transaction.submit(function(err, res) {
                if (err) {
                    console.log('Report error: ' + JSON.stringify(err));
                }
                else {
                    //IT DOES SOMETHING
                }
            });

The error I get as err is the one reported on top: {"result":"tejMaxFeeExceeded","result_message":"Error","engine_result":"tejMaxFeeExceeded","engine_result_message":"Error","message":"Error"}

**Comment by tuloski** [comment]
When normally I have a "tejMaxFeeExceeded" without unhandled error I have the full answer as:

Report error: {"result":"tejMaxFeeExceeded","result_message":"Max fee exceeded","engine_result":"tejMaxFeeExceeded","engine_result_message":"Max fee exceeded","message":"Max fee exceeded","tx_json":{"Flags":0,"TransactionType":"OfferCreate","Account":"XXX","TakerPays":XXX,"TakerGets":XXX,"OfferSequence":39881,"Sequence":39882,"SigningPubKey":"XXX","Fee":"13032"}}

**Comment by tuloski** [comment]
It seems the error doesn't pass this test: https://github.com/ripple/ripple-lib/blob/fc38a9853d33312302cfb58436e2d9d9bd623fa3/src/js/ripple/remote.js#L519 (ripplerm found this)

**Comment by weitaolee** [comment]
nodejs version 0.12.0 :I use ripple-lib never other error like tejMaxFeeExceeded or tejMaxLedger, only a error like this .
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)

 I see ws.onerror has a listener.  so I do not know where has this unhandled error.
https://github.com/ripple/ripple-lib/blob/a9b7d7d793c760ddcac3de4ace4e8e411894deba/src/js/ripple/server.js#L444

**Comment by crazyquark** [comment]
I increased my max ledger sequence to avoid this:
after a transaction = remote.createTransaction
I do:
transaction.lastLedger(remote.getLedgerSequence() + 10);
