### ISSUE TITLE
Adding a event listener to Account and Remote shouldn't trigger automatic subscription

### ISSUE THREAD

**Issue by emoitzi** [ripple/ripple-lib#300]
Both classes issue subscribe requests when listeners to certain events are added. 
I believe a average developer wouldn't expect such a behavior, and thus it should be removed. 

Also creating an Account triggers this behavior, because the constructor automatically adds a 'transaction' listener. IMHO this should be removed as well.

Plus I can guarantee that this functionality is not used by anyone, because it is broken:
 * This line is still using Remote.requestSubscribe instead of Remote.requestSubscribe
https://github.com/ripple/ripple-lib/blob/423ec7d08af997e77866052653f324b9ed1b1920/src/js/ripple/account.js#L46

 * the following lines calls Request.add_account instead of Request.addAccount

 * and until the recent commit 2833a7b66e696dab427464625077f9b93092d0d5 this was also true for Remote:
request_subscribe -> requestSubscribe
https://github.com/ripple/ripple-lib/blob/98f40abfc3aa74dec5067a2d90002756cc8acd01/src/js/ripple/remote.js#L220

**Comment by wltsmrz** [comment]
> Both classes issue subscribe requests when listeners to certain events are added. I believe a average developer wouldn't expect such a behavior, and thus it should be removed.

I kind of agree. It's been discussed before but we didn't have compelling reason to change. Thanks for your input on the API. To be clear, you're suggesting a separate `.subscribe()` method and getting rid of automatic subscription/unsubscription via added/removed event listeners, right?

> Plus I can guarantee that this functionality is not used by anyone, because it is broken:

I can guarantee that it is! [under_score and camelCase methods work with Remote, Request, etc.](https://github.com/ripple/ripple-lib/blob/develop/src/js/ripple/index.js#L38-L62), but these under_score methods have been deprecated for a long time, so they ought to be removed.

**Comment by emoitzi** [comment]
>To be clear, you're suggesting a separate .subscribe() method and getting rid of automatic subscription/unsubscription via added/removed event listeners, right?

Right.

 > I can guarantee that it is! under_score and camelCase methods work with Remote, Request, etc.,

Oh, I overlooked that piece. Looks like your guarantee supersedes mine. :innocent:
