### ISSUE TITLE
requestAccountTx missing dates

### ISSUE THREAD

**Issue by Ossip** [ripple/ripple-lib#323]
hi, 
the transactions in remote.requestAccountTx() don't include the 'date' when 
binary is kept as true (default). With binary=false it works.
It took me a moment to find it, so I suggest documenting this somewhere if it can't be added easily?

**Comment by wltsmrz** [comment]
This could be done perhaps more efficiently at a lower level, but it looks like all transactions should have a date with the new API https://github.com/ripple/ripple-lib/blob/5ac2576fcf00a94358a574c299761a7a38f90bd1/src/api/ledger/transaction.js#L18-L39
