### ISSUE TITLE
Ordedbook support for synthetic offers

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#341]
ENHANCEMENT
Orderbooks requests should support the upcoming autobridge.
For example returning the orderbook filled with standard IOU:IOU offers plus synthetic offers.

**Comment by lumberj** [comment]
See the latest release candidate: https://github.com/ripple/ripple-lib/releases/tag/0.12.5-rc2

**Comment by tuloski** [comment]
Perfect :) thanks
