### ISSUE TITLE
sjcl-custom linting on Travis

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-lib#346]
If we keep sjcl at all, the custom stuff will likely be pushed towards getting merged into sjcl.

We probably want to use the es5 style guide settings?

**Comment by clark800** [comment]
You can do `/* eslint-disable no-var, no-param-reassign */` in the sjcl-custom files to allow es5 syntax.

**Comment by sublimator** [comment]
Is there also a way to make it cry if I use `let` or `const` or whatever other es6 feature?

**Comment by clark800** [comment]
There is if you setup the config file using the es6 environment. It looks like it might be cleaner anyways: https://github.com/eslint/eslint/issues/2072
