### ISSUE TITLE
Orderbook emits trade events with OfferCancel transaction data too!

### ISSUE THREAD

**Issue by lieefu** [ripple/ripple-lib#376]
It seems to these code not work.
const isOfferCancel =
    transaction.transaction.TransactionType === 'OfferCancel';
  const transactionOwnerFunds = transaction.transaction.owner_funds;

  function handleNode(node) {
    switch (node.nodeType) {
      case 'DeletedNode':
        self.deleteOffer(node, isOfferCancel);

        // We don't want to count an OfferCancel as a trade
        if (!isOfferCancel) {
          takerGetsTotal = takerGetsTotal.add(node.fieldsFinal.TakerGets);
          takerPaysTotal = takerPaysTotal.add(node.fieldsFinal.TakerPays);
        }
        break;

**Comment by clark800** [comment]
I see that all the code you posted is from orderbook.js: Orderbook.prototype.notify. Can you clarify what the problem is? It might help if you provide code that reproduces the problem.
