### ISSUE TITLE
Seed.parse_json looseness

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-lib#468]
After a recent patch, basically any string with length >= 1 is now parsed as a valid secret (Seed), whereas before at least any string starting with an `s` was parsed as base58 and if it wasn't valid, that was the final judgement.

In transaction-test.js, some tests now pass for different reasons than it seems like was intended. Specifically, before an `error` was emitted on the transaction object when the `._secret` was invalid due to the string "s....." not being a valid base58 checksum encoded seed, and now it's being emitted solely because the passphrase interpretation of the string doesn't match the address (Seed.get_key(address)). 

I think if anything, we should be tightening loose nuts, rather than loosening them.

**Comment by sublimator** [comment]
See: https://github.com/ripple/ripple-lib/blob/develop/test/transaction-test.js#L458-L477

**Comment by clark800** [comment]
Isn't the problem that `parse_json` basically accepts three different encodings? Is there anything reasonable we can do without breaking backwards compatibility?

**Comment by sublimator** [comment]
2 encodings plus 1 whatever you wanna call passphrase parsing, which sha512
hashes the string and takes first 128bits.

The way it is now makes a mockery of the base58 checksum encoding
properties.

I'm not sure the ultimate answer (just base58 / hex probably - and break
back compat). I'd probably restore the any string starting with 's' parsed
only as base58 in the mean time though.
