### ISSUE TITLE
Uncaught error: tejMaxFeeExceeded

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#523]
Sometimes it happens an uncaught error with transaction fee exceeded but not always. I noticed from the error of the transaction that when the error happens there is a different tej message.
Below the error that doesn't cause the uncaught event:

```
Report error transaction: {"result":"tejMaxFeeExceeded","result_message":"Max fee exceeded","engine_result":"tejMaxFeeExceeded","engine_result_message":"Max fee exceeded","message":"Max fee exceeded","tx_json":{"Flags":0,"TransactionType":"OfferCreate","Account":"rXXX","TakerGets":"XXX","TakerPays":{"value":"XXX","currency":"XXX","issuer":"XXX"},"OfferSequence":25572,"Sequence":25573,"SigningPubKey":"XXX","Fee":"13500"}}
```

Below the error that triggers the uncaught event, and the stack trace:
```
Report error transaction: {"result":"tejMaxFeeExceeded","result_message":"Error","engine_result":"tejMaxFeeExceeded","engine_result_message":"Error","message":"Error"}

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transaction.EventEmitter.emit (events.js:74:15)
    at Transaction.<anonymous> (/home/odroid/node_modules/ripple-lib/dist/npm/transactionmanager.js:194:19)
    at Transaction.g (events.js:180:16)
    at Transaction.EventEmitter.emit (events.js:117:20)
    at TransactionManager._request (/home/odroid/node_modules/ripple-lib/dist/npm/transactionmanager.js:666:6)
    at resubmitTransaction (/home/odroid/node_modules/ripple-lib/dist/npm/transactionmanager.js:479:10)
    at iterate (/home/odroid/node_modules/ripple-lib/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/odroid/node_modules/ripple-lib/node_modules/async/lib/async.js:162:9)
    at /home/odroid/node_modules/ripple-lib/dist/npm/transactionmanager.js:483:11
```

Maybe the fault is of rippled that returns a strange tej message.

**Comment by lumberj** [comment]
What version are you running?

**Comment by tuloski** [comment]
Latest release taken from npm.

**Comment by clark800** [comment]
To debug this, we would probably have to be able to reproduce it. Can you provide a complete program that reproduces the issue?

It looks like the error is coming from this line: https://github.com/ripple/ripple-lib/blob/develop/src/core/transactionmanager.js#L201

I'm not sure what the API usage is supposed to be here because it doesn't seem to be documented, but maybe you just have to add a listener for error events on the `Transaction` object?

**Comment by tuloski** [comment]
I think there is already an error event listened on Transaction.
The strange thing is that (see above the first post) when there is no uncaught event, the transaction error reports: "result_message":"Max fee exceeded", while when the uncaught event happens the transaction error reports: "result_message":"Error".
Unfortunately I'm not a JS experts and events and callbacks are hard for me to understand, so I can't understand much from the code.

This is a part of my code where I submit the transaction:


var transaction = remote.createTransaction('OfferCreate', {
		            account: MY_ADD,
		            taker_pays: TAKER_PAYS,
		            taker_gets: TAKER_GETS,
		            cancel_sequence: seq
		        });

				transaction.on('final', function(){
		        	//console.log('Finalized offer: ' + JSON.stringify(TAKER_PAYS));
		    	});
		        
		
		        transaction.submit(function(err, res) {
		            if (err) {
		                console.log('Report errore offerta: ' + JSON.stringify(err));
						callback(err);
		            }
		            else {
		                //off_Created++;
		                //console.log('Offerte Create: ' + offerteCreate);
		                //console.log('Piazzata offerta e cancellata precedente. Issuer:' +issuer2sell + ' Amount:' + amount);
						callback(res);
		            }
		        });

**Comment by clark800** [comment]
Have you tried adding this?
```
  transaction.on('error', function(error) {
    console.log(error);
  });
```

**Comment by tuloski** [comment]
@clark800 : It seems that with the listener you wrote it doesn't crash. Even in the case that the reported error from the transaction is the bad one.

**Comment by tuloski** [comment]
Hey guys,

I have a simple question for ripple-lib that I didn't manage to make it works.

How to get a screenshot of an autobridged orderbook?

I've seen that the orderbook object has everything to build the autobridged offers, but there are too many callback I can't follow where and whether the mergedOffers are returned.

With remote.requestBookOffers I get only the non-bridged ones.

I'm using 0.12.6. Thanks


Regards,

Michele
