### ISSUE TITLE
Browser build: Cannot find module "net"

### ISSUE THREAD

**Issue by mesca** [ripple/ripple-lib#532]
The current version of ripple-lib, when built for browser, returns the following error: `Cannot find module "net"`.
Additionally, the `ripple.sjcl` is not exposed anymore. Any reason for this?

**Comment by clark800** [comment]
The current version of ripple-lib (0.12.6) does expose `sjcl`. What version are you using?

**Comment by mesca** [comment]
The latest from the develop branch (0.13.0-rc6).

**Comment by clark800** [comment]
That's a beta version of the next release, which no longer uses sjcl and has a new API, see the release notes in HISTORY.md.

I'll look into: `Cannot find module "net"`

**Comment by mesca** [comment]
Thanks. I just built 0.12.6 and it now works as expected.

**Comment by mesca** [comment]
Fixed in 0.13.0-rc8 with [#533](https://github.com/ripple/ripple-lib/pull/533).
