### ISSUE TITLE
getting 404 server response

### ISSUE THREAD

**Issue by charnasol** [ripple/ripple-lib#617]
We have installed and have the ripple system up. However after customizing, on the sign up and login links we get a 404 documents/file/link not found on our server return. We would like help on this as we would like to launch our ripple asap. Thank you!

**Comment by clark800** [comment]
Please redirect inquiries to support@ripple.com

**Comment by charnasol** [comment]
They directed me here

James McEvoy
CEO

**Comment by clark800** [comment]
They must have made a mistake since this issue is not related to ripple-lib. I spoke with Julian Martinez of Technical Services and he suggests raising the question on the forum: https://forum.ripple.com/
