### ISSUE TITLE
Running rippled and using ripple-lib

### ISSUE THREAD

**Issue by Kekec852** [ripple/ripple-lib#673]
Hi,

i have found an pickle running ripple-lib with my rippled server (server is at: `0.30.1-b10`).

rippled: `0.30.1-b10` build from develop branch today
ripple-lib: `0.16.2`
nodejs: `4.2.3`
npm: `2.14.7`

I'm using following code to connect:
```javascript
var ripple = require('ripple-lib');
var Remote = ripple.RippleAPI;

var remote = new Remote({
    server: 'ws://192.168.8.83:6006'
    //server: "wss://s1.ripple.com"
});

remote.connect().then(function () {
    console.log("Starting ... ");
}).catch(console.error);

remote.on('error', function (errorCode, errorMessage) {
    console.log(errorCode + ': ' + errorMessage);
});

```
When i connect to my server i receive this message but not every time:
```
[TypeError: Cannot read property 'split' of undefined]
```

When i connect to public ripple server everything is working every time. 

What am I missing.

Best regards,
Martin Hribar

**Comment by clark800** [comment]
Thanks, should be fixed by this (not yet released to npm): https://github.com/ripple/ripple-lib/pull/675

**Comment by Kekec852** [comment]
This pull-request fixes the TypeError, but now different problem, that probably has same cause that lead to discovery of TypeError. 

For unknown reason (a least for me) my ripple server is returning empty leader version. 

Wish me a luck at finding miss configuration :P

**Comment by Kekec852** [comment]
Found it ... it helps if you add `[validators]` to rippled.cfg :smile:
