### ISSUE TITLE
Uncaught Error: Cannot find module "JSONStream"

### ISSUE THREAD

**Issue by zolekm** [ripple/ripple-lib#676]
Hi,
I use ripple lib version 0.16.2

When run application in browser i get this error Uncaught Error: Cannot find module "JSONStream"

Is there something i'm missing?

Best regards,
Matija

**Comment by clark800** [comment]
ripple-lib no longer supports running in browsers, only NodeJS. We would likely accept pull requests to make it work in browsers, but as there is no browser testing in place, it may break again in the future unless the pull request also adds browser testing.
