### ISSUE TITLE
documentation for MaxLedgerVersion doesn't mention "null" option

### ISSUE THREAD

**Issue by mDuo13** [ripple/ripple-lib#683]
You can specify "null" for `MaxLedgerVersion` in tx instructions to explicitly exclude the `LastLedgerSequence` parameter from the prepared transaction. (For example, if you're going to prepare/sign a transaction and keep it on hold indefinitely.) However, this option is not documented. It should be.

**Comment by clark800** [comment]
It appears to be documented, where specifically is it missing?

**Comment by mDuo13** [comment]
Ah. >"< It's not on https://ripple.com/build/rippleapi/ which appears to be partly my fault. That documentation has not been updated to reflect additional releases of ripple-lib. 

That's a problem with our release process, not the documentation.
