### ISSUE TITLE
Connection woes

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-lib#685]
connect() currently doesn't seem to poll with any kind of decay if a server isn't ready, nor does it reject(), which means a user will have to implement this themselves. 

I noticed this when porting the rippled integration tests to use the latest version of ripple-lib, where the server needs to do things like load a ledger dump, and whatever else, before bringing up the ports. This can take quite some time. It's possible of course to just set a long timeout, but that's not an acceptable solution. You could `expect` a certain line from the logging output to determine the ready state of rippled for connections but the tests must also work with servers that have been started by them selves (running in a debugger for example)
##

**Comment by sublimator** [comment]
Remote also emitted 'connect', 'disconnect' events which were quite useful

**Comment by sublimator** [comment]
```js
_onUnexpectedClose() {
    this._ws = null;
    this._isReady = false;
    this.connect().then();
  }
```
`    this.connect().then();`

Then? go on a date?

**Comment by clark800** [comment]
We have to call `.then` to execute the promise, but there is nothing else that needs to be done because inside the `connect()` code the `connected` event will fire and cause requests to resume.

**Comment by sublimator** [comment]
> there is nothing else that needs to be done because 

I could see that, but I didn't know you had to 'trigger' execution of a promise via then() 

> We have to call .then to execute the promise

Wait, what? Is that normal behaviour for Promises?

```js
> var p = new Promise(function(resolve, reject) {console.log('Go!')})
Go!
```

**Comment by clark800** [comment]
> Wait, what? Is that normal behaviour for Promises?

Well, ES6 does require non-lazy execution so `.then()` could be omitted here, but some other Promises/A+ compliant libraries do lazy execution. Using `.then()` everywhere just makes it compatible with all Promise implementations.

**Comment by sublimator** [comment]
Hrmmm, I guess that should be obvious to people familar with various
implementations of Promise. What is bluebird's behaviour?

**Comment by clark800** [comment]
I think all the major libraries use immediate execution, though I'm curious why because lazy execution seems better in that you don't waste time if "then" never gets called.

**Comment by sublimator** [comment]
then() called with no params, hrmmm. I'd almost like that to be an error

Have you done any testing swapping out Promise impls? Is that actually
something likely to be done?

**Comment by clark800** [comment]
No and no

**Comment by intelliot** [comment]
@sublimator I don't quite understand what's going on here :) Is there an improvement we should make? Otherwise, I think we can close this issue.

**Comment by sublimator** [comment]
@intelliot It's been so long that I can't recall the details, or if the issue has been solved since, though I think it's to do with the auto reconnection not working unless it first successfully connects? From the issue wording, It seems I was having issues with rippled not being ready and accepting connections.

**Comment by intelliot** [comment]
Thanks for clarifying! I'm going to close this issue, but feel free to open a new one (with more details) if you encounter the issue again.

**Comment by sublimator** [comment]
i don’t use ripple-lib anymore :)
