### ISSUE TITLE
Orderbook real-time stream

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#697]
Hi guys,
I'm starting to play with new RippleAPI to convert all my old code.
But in the documentation I didn't see any way to subscribe to a book with some push (stream) API for real-time. 
Is now the only way to get an orderbook by polling with "getOrderbook"?

**Comment by shekenahglory** [comment]
the orderbook module has been separated out into ripple-lib extensions - https://github.com/ripple/ripple-lib-extensions
