### ISSUE TITLE
add offerSequence functionality to prepareOrder function

### ISSUE THREAD

**Issue by ripplejnr** [ripple/ripple-lib#700]
It is currently not possible to cancel/replace a previous trade with a new trade using ripple-lib.This functionality is available in rippled however with the 'offerSequence' parameter.

Is it possible to build this in the ripple-lib API?

I am now 'hacking' the offerSequence parameter in the 'prepared' order and that works, but it would be cleaner if the Ripple-Lib interface would support this parameter natively.

rgds.
Jn_r

**Comment by mDuo13** [comment]
For others who might find this ticket, here's a forum link explaining the workaround for now:
https://forum.ripple.com/viewtopic.php?f=2&t=15925#p72451

**Comment by clark800** [comment]
`orderToReplace` option added in https://github.com/ripple/ripple-lib/pull/727
