### ISSUE TITLE
Boilerplate error

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#710]
There is a small error in the boilerplate code here: https://ripple.com/build/rippleapi/

```
const {RippleAPI} = require('ripple-lib');
```
should be
```
const RippleAPI = require('ripple-lib').RippleAPI;
```

**Comment by clark800** [comment]
This isn't technically an error because the docs state that you should use Babel for ES6 support. But it would be good to make the docs work with Node v4+ to get rid of the Babel dependency for running.
