### ISSUE TITLE
getTransactions(address): 'BigNumber() not a number...'

### ISSUE THREAD

**Issue by chjcook** [ripple/ripple-lib#715]
When calling the function getTransactions(_address_), the promise catches an error:
{ [BigNumber Error: new BigNumber() not a number: unavailable] name: 'BigNumber Error' }

Code:

```
api.connect()
.then(() => {
    const address = 'rhpPzYgx9YrmbeafoncJpAMYyUwebdS6o8';
    return api.getTransactions(address);
})
.then(transactions => {
    console.log(JSON.stringify(transactions, null, 2));
})
.then(() => {
  return api.disconnect();
}).catch(console.error);
```
##

**Comment by intelliot** [comment]
@chjcook Sorry for the long delay. I ran the code you posted above, and it worked fine for me. Please feel free to open a new issue if the problem persists.
