### ISSUE TITLE
html page not running

### ISSUE THREAD

**Issue by swdpankaj** [ripple/ripple-lib#716]
I am beginner to use ripple. I downloaded this script and trying to run this page "localintegrationrunner.html". But the files and folders are not found in this script "mocha/mocha.css", "mocha/mocha.js" and "ripple-for-web-tests.js". I am able to connect ripple using this script https://github.com/ripple/ripple-dev-portal/tree/master/content/code_samples/rippleapi_quickstart but I don't know how to pass HTML form data to ripple server using HTML page. I am using php with javascript. So anyone can assist me to create a first web form to submit the transaction.

**Comment by whotooktwarden** [comment]
What version of ripple-lib are you using?  Could perhaps be related to #702

**Comment by swdpankaj** [comment]
I am using ripple-lib-0.16.5

On 4/26/16, Taylor Warden <notifications@github.com> wrote:
> What version of ripple-lib are you using?  Could perhaps be related to #702
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ripple/ripple-lib/issues/716#issuecomment-214592867


-- 
*Thanks and Regards*

*Pankaj Kumar*
*swd*

**Comment by darkdarkdragon** [comment]
@swdpankaj What are you trying to achieve? If you want to contact rippled server from browser, you will need to write javascript code that will run in the browser, will take data from you form and send it to rippled server using ripple-lib. 
If you want to contact rippled server from you own server, you should use nodejs instead of php.

localintegrationrunner.html is used in tests only, you shouldn't take it as example.

**Comment by swdpankaj** [comment]
I want to develop a website which will use ripple api for fund
transfer. For this I downloaded the source code from
https://github.com/ripple/ripple-lib/releases.

I have successfully connected using with my html page using this
script. https://github.com/ripple/ripple-dev-portal/tree/master/content/code_samples/rippleapi_quickstart


But I don't know how to execute json code using javascript and how to
start my first application web form which will use the api for fund
transfer.

I am using nodejs with version ripple-lib-0.16.5.

Can you provide me example to begin my first HTML page with html
form.which is used to submit transaction.



On 4/27/16, Ivan Tivonenko <notifications@github.com> wrote:
> @swdpankaj What are you trying to achieve? If you want to contact rippled
> server from browser, you will need to write javascript code that will run in
> the browser, will take data from you form and send it to rippled server
> using ripple-lib.
> If you want to contact rippled server from you own server, you should use
> nodejs instead of php.
>
> localintegrationrunner.html is used in tests only, you shouldn't take it as
> example.
>
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ripple/ripple-lib/issues/716#issuecomment-214867689


-- 
*Thanks and Regards*

*Pankaj Kumar*
*swd*

**Comment by clark800** [comment]
For technical support please contact support@ripple.com
