### ISSUE TITLE
No Promise

### ISSUE THREAD

**Issue by Kekec852** [ripple/ripple-lib#717]
Hi,

I have encountered an pickle. I'm trying to create settings on account calling `api.prepareSettings(address, settings)`, but doesn't return Promise object. It's waiting on something. 

My code:
```javascript
var api = new Remote({
    server: "wss://s.altnet.rippletest.net:51233"
});

api.on('error', function (errorCode, errorMessage) {
    logger.log('debug', errorCode + ': ' + errorMessage);
});
api.on('connected', function () {
    logger.log('debug', 'connected');
});
api.on('disconnected', function (code) {
    logger.log('debug', 'disconnected, code:', code);
});

api.connect().then(function () {
    //this is executed
   logger.log('info', 'Connected');
    var promis = api.prepareSettings(config.master.account_id, {
        defaultRipple: true,
        "memos": [
            {
                "type": "test",
                "format": "plain/text",
                "data": "Test text"
            }
        ]
    }, {
        maxFee: 0.014
    });
    
    //i never get to here
    logger.log('debug', promis);
    logger.log(util.inspect(promis));

    promis.then(function (tx) {
        logger.log('debug', tx);
    }).catch(function (err) {
        logger.log('error', err);
    });
});
```

My investigation into ripple-lib code lead me to problem with schema validator, but i could be wrong.

P.S.: On more testing i found out that problem is in maxFee directive. If I don't use it, everything works like it should.

Best regards

**Comment by Kekec852** [comment]
I found the problem ... maxFee MUST be a string it fails without error! That might be a bug.

**Comment by clark800** [comment]
It will show an error if you add the `.catch(console.error)` from the Boilerplate script https://github.com/ripple/ripple-lib/blob/develop/docs/index.md#boilerplate
