### ISSUE TITLE
Missing interface for order replacement

### ISSUE THREAD

**Issue by codedot** [ripple/ripple-lib#722]
[`OfferCreate`](https://ripple.com/build/transactions/#offercreate) has an optional parameter `OfferSequence` to specify an order to delete before creating a new one. However, in the latest `ripple-lib` version the `prepareOrder()` routine does not support that option. This option needs to be implemented to save fees and time for market makers.

**Comment by mDuo13** [comment]
this is a dupe of #700

**Comment by clark800** [comment]
Closing as duplicate
