### ISSUE TITLE
Missing interface for path_find

### ISSUE THREAD

**Issue by codedot** [ripple/ripple-lib#729]
RippleAPI is currently missing interface for the `path_find` request. Currently, the only pathfinder interface in RippleAPI seems to be the `getPaths()` method which is based on a simpler version of pathfinder, namely `ripple_path_find`.
##

**Comment by intelliot** [comment]
@codedot What's your use case for `path_find`?

In the latest version of ripple-lib, you can use the `request` method to call any of the rippled APIs, including `path_find`.

**Comment by codedot** [comment]
My use case for `path_find` used to be a market-taking bot. However, reimplementing that old piece of software using the new low-level method `request` seems to require too much work.

**Comment by intelliot** [comment]
Is there an old path_find method that we can bring back?

I’ve only been working on ripple-lib for about a year so I’m wondering if you’re referring to something that was in an old version.

**Comment by codedot** [comment]
In `ripple-lib@0.10.0`, there was a method called `pathFind` which provided a convenient enough interface for the `path_find` request.

**Comment by intelliot** [comment]
Ah, that was 3+ years ago. Yes, I think this is a great idea.

Anyone out there interested in contributing a PR? (@yxxyun?)

**Comment by mvadari** [comment]
Resolved with #1503

**Comment by mvadari** [comment]
Resolved by #1576 as well
