### ISSUE TITLE
getTransactions MissingLedgerHistoryError

### ISSUE THREAD

**Issue by caipeng-hrv** [ripple/ripple-lib#732]
Hello
      when i use getTransactions with options where has not limit or the limit is not equal the 
 length of transactions,it get the MissingLedgerHistoryError.
    where i found the code is 
```
   if (options.limit && transactions.length === options.limit) {
    if (options.earliestFirst) {
      maxLedgerVersion = _.last(transactions).outcome.ledgerVersion;
    } else {
      minLedgerVersion = _.last(transactions).outcome.ledgerVersion;
    }
  }
```
is it correct? why options.limit must equal transactions.length even i do not know transactions.length. 

i use the code it will work fine.
```
if (options.earliestFirst) {
    maxLedgerVersion = _.last(transactions).outcome.ledgerVersion;
  } else {
    minLedgerVersion = _.last(transactions).outcome.ledgerVersion;
  }
```

**Comment by clark800** [comment]
If you don't specify limits, it will try to get _all_ of the history and most rippled servers don't store all of the history. You can specify `minLedgerVersion` and/or `maxLedgerVersion` and/or `limit` to prevent this problem.

**Comment by caipeng-hrv** [comment]
ok,thank you.

**Comment by webtech2412** [comment]
I am facing the same issue, i have set up full node on my server. Everything is working but getTansactions is throwing error error - error [ValidationError(instance.options.maxLedgerVersion is not exactly one from [subschema 0],[subschema 1])]

I tried passing "minLedgerVersion" from my getserverinfo function using the completeLedger values but it is not working and giving MissingLedgerHistoryError(Server is missing ledger history in the specified range)]

I observe completeLedger is giving me random values. I tried to split and use min/max ledger version but that is not working as the format is getting changed
Somitime it give like this
completeLedger ="54873243-54888233,54888334-54888352,54888587-54888604,54888706-54888755,54888921-54888922,54889023-54889061,54889170-54889190,54889347-54889402,54889506-54889562,54889665-54889950,54890141-54890169,54890448-54890460,54890561-54890582,54890694-54890732,54890868-54891060,54891231-54898249"

and some time "completeLedgers": "54873243-54888233,54888334",

How i can resolved this. getTransactions is supposed to work with address only and options are optional but it is not working. Please help.

**Comment by YoleYu** [comment]
I meet this error, after add minLedgerVersion the error is gone.
`   const options = {
        minLedgerVersion: 1654715,
        types:["payment"],
        excludeFailures:true,
        limit: limit,
        initiated: false,
        earliestFirst:true,
        //start:start
      }`
But if I add param start, 'ValidationError' comes out. After read the document, I know start should not be used with minLedgerVersion at the same. Then changed option as follow, MissingLedgerHistoryError comes out again. I don't know the reason.
 
    const options = {
        //minLedgerVersion: 1654715,
        types:["payment"],
        excludeFailures:true,
        limit: limit,
        initiated: false,
        earliestFirst:true,
        start:start
      }
