### ISSUE TITLE
Browser-Build Reference Error in Javascript

### ISSUE THREAD

**Issue by pftq** [ripple/ripple-lib#733]
I used the directions here to build a browser-compatible JS file:
https://ripple.com/build/rippleapi-beginners-guide/#build-instructions

 But when I run the example HTML, I get the following error in Chrome:
ripple-0.17.1.js:8284 Uncaught ReferenceError: _ is not defined

That line in the js file is:
module.exports = _;
##

**Comment by bensharaf** [comment]
The browser version of `ripple-lib` expects you to include lodash in your webpage. Try adding

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.15.0/lodash.js"></script>
```

**Comment by pftq** [comment]
Thanks, this was not clear to me from the project or developer guide.

**Comment by intelliot** [comment]
The example code has been updated to include lodash. Closing.
