### ISSUE TITLE
Account argument for method 'getOrderbook' should be optional

### ISSUE THREAD

**Issue by flxh** [ripple/ripple-lib#735]
The ripple-lib api shouldn't throw an error when you omit or pass `null` for the first argument, which is the account used as perspective. 
Because the corresponding rippled command 'book_offers' already defaults the account to ACCOUNT_ONE when the account parameter is omitted. So from that perspective passing `null` as account should be absolutely fine.

**Comment by clark800** [comment]
The ripple-lib API does not aim for consistency with the rippled API; it is intended to be a simplified interface, so we intentionally avoided reproducing all the quirks of the rippled API.
