### ISSUE TITLE
api.getOrderbook freezes on new iphones

### ISSUE THREAD

**Issue by pftq** [ripple/ripple-lib#762]
See this thread:
https://www.xrpchat.com/topic/4477-apigetorderbook-freezing-on-iphone/

It only started happening a few days ago, no code changes, same phones, same ripplelib version (tested 0.17.1-7 - no effect).  So it seems like something to do with the rippled servers and not the library itself.

**Comment by bachase** [comment]
Thanks for reporting. It appears this is due to https://github.com/MikeMcl/bignumber.js/issues/120, which is due to a bug in safari https://bugs.webkit.org/show_bug.cgi?id=170264.  We can investigate a workaround.

**Comment by pftq** [comment]
Glad it was identified. Note it affects transactions and orders as well,
not just orderbook.

**Comment by pftq** [comment]
Any update on this? It appears that any site using ripplelib is
inaccessible to the latest iPhone, including GitHub and any site that
offers trading directly through RCL.

On May 12, 2017 1:43 PM, "pftq" <pftq@pftq.com> wrote:

Glad it was identified. Note it affects transactions and orders as well,
not just orderbook.

**Comment by Julyyq** [comment]
I met same problem, is there any solution yet?

**Comment by sublimator** [comment]
XRP price is fine, what you mean?? Haha

**Comment by Julyyq** [comment]
@sublimator 😓 many apis broke because of this issue.

**Comment by sublimator** [comment]
Yeah, I don't know why they don't work out a fix

**Comment by sublimator** [comment]
I used to work at ripple and know ripple pretty well so I will try take a
look.

**Comment by Julyyq** [comment]
I see `bignumber.js` library author fix the issue, but last updated time of `ripple-lib `was 2 month ago, can't believe. 
Thanks very much, this bug block me several days.

**Comment by sublimator** [comment]
So they just need to update package.json??

On Jun 28, 2017 3:08 PM, "Allen.Young" <notifications@github.com> wrote:

I see bignumber.js library author fix the issue, but last updated time of
ripple-libwas 2 month ago, can't believe.
Thanks very much, this bug block me several days.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ripple/ripple-lib/issues/762#issuecomment-311588125>,
or mute the thread

**Comment by sublimator** [comment]
Looks like it needs to be updated in a few dependencies too: ripple-hashes and ripple-lib-transactionparser

**Comment by Julyyq** [comment]
@sublimator Ripple develop with low speed. :)

**Comment by sublimator** [comment]
I know :/

**Comment by Julyyq** [comment]
@sublimator So it's the reason you leave. haha

**Comment by sublimator** [comment]
I would open up some pull requests, but when I have some open from January
already, it's hard to get the motivation :)

**Comment by Julyyq** [comment]
@sublimator I will use your fork repo. You are a good man.

**Comment by sublimator** [comment]
Don't use my fork! It's ancient!

Just try updating the package.json for bignumber.js in each dependency:
ripple-lib
ripple-hashes
ripple-lib-transactionparser

**Comment by Julyyq** [comment]
Alright I'll try to update package.json.

**Comment by Julyyq** [comment]
@sublimator  It worked! I love u.

**Comment by sublimator** [comment]
Happy Days!

Remember to run the test suites!

**Comment by pftq** [comment]
Can you upload or share the compiled ripple js file? Much appreciated.
Thank you

**Comment by Julyyq** [comment]
@pftq You're welcome. 😊
[ripple-0.17.7-min.js.zip](https://github.com/ripple/ripple-lib/files/1110974/ripple-0.17.7-min.js.zip)

**Comment by pftq** [comment]
Thanks - do you have the non-min version too?

**Comment by Julyyq** [comment]
@pftq 
[ripple-0.17.7.js.zip](https://github.com/ripple/ripple-lib/files/1114113/ripple-0.17.7.js.zip)

**Comment by pftq** [comment]
Thanks again for the patched version.  The official version is pretty much non-functional until this is patched.  Hopefully they notice soon.

**Comment by intelliot** [comment]
This was fixed in [0.17.8](https://github.com/ripple/ripple-lib/releases/tag/0.17.8). Thank you!
