### ISSUE TITLE
getTransactions Error

### ISSUE THREAD

**Issue by cometburn** [ripple/ripple-lib#763]
Using ``ripple-0.17.4.js`` shows an error (see attached image)

lodash version ``4.16.4``

![screen shot 2017-05-20 at 14 53 27](https://cloud.githubusercontent.com/assets/12859640/26273876/3b85bd66-3d6d-11e7-8e43-c63a09df80dd.png)

**Comment by lastgox** [comment]
I got same error.
Please fix it.

**Comment by Julyyq** [comment]
+1
![screenshot 2017-06-30 12 09 55](https://user-images.githubusercontent.com/2620575/27720880-2613a9d8-5d8f-11e7-91ed-d523970e96f5.png)

**Comment by intelliot** [comment]
I believe this was fixed in 0.18.1 (2018-01-27). Please let us know if you find otherwise. Thanks!
