### ISSUE TITLE
Success transaction but account wasn't activated.

### ISSUE THREAD

**Issue by ydlee1227** [ripple/ripple-lib#768]
I've sent ripples onto my ripple adress 
BUt it wasn't activated the adress. And I cannot find my ripples

Adress :  rsG1sNifXJxGS2nDQ9zHyoe1S5APrtwpjV

23D7AE2C4F39B9C3ECE1CCFD1BF49CB4AACD0FE4F9E943DFB7FD527D571314A7
This is my transaction ID.
https://xrpcharts.ripple.com/#/transactions/23D7AE2C4F39B9C3ECE1CCFD1BF49CB4AACD0FE4F9E943DFB7FD527D571314A7
It shows it is successful. But it hadn't activated my adress.
Recently, I've sent 20 more ripple to this adress. It could activate my account.
How can I find prior ripples?
Thank you

**Comment by intelliot** [comment]
@ydlee1227 How do you know it wasn't activated?

The transaction looks successful and the destination address appears to have the funds.

**Comment by tbcooney** [comment]
@ydlee1227 Did you ever find the prior Ripples?

**Comment by intelliot** [comment]
It looks like the XRP was sent and the account is active. However, please feel free to open a new issue if you spot a problem.
