### ISSUE TITLE
deriveKeypair and deriveAddress

### ISSUE THREAD

**Issue by pftq** [ripple/ripple-lib#770]
Is there a way to access these functions? They would be useful to return the address from a secret key and verify a correct address-secret key pair.  If not, could they be exposed? Thanks

**Comment by sublimator** [comment]
https://github.com/ripple/ripple-keypairs

**Comment by pftq** [comment]
I'm aware of that library.  However, it's 2 years old and would be useful to have available in the main ripplelib (especially since the code is already in ripplelib, just not exposed through API).

**Comment by sublimator** [comment]
2 years old= pretty stable. Not a moving target

Convenience of it being exported from ripple lib aside ...

**Comment by pftq** [comment]
Not sure why this is a debate.  The code is already in ripplelib - it just needs to be exposed.  It would help developers to find everything in one place rather than have to locate an additional library that contains the duplicate code.

**Comment by sublimator** [comment]
Not sure why you think this is a debate :)

I have no authority to add it to ripple-lib, just saying that you can use
ripple-keypairs and get on with life while waiting for someone from ripple
that can actually make the changes you want.

**Comment by pftq** [comment]
Ok, it just wasn't clear to me what your point was.  I already have the functionality on my end by adding the 4 lines of code to ripplelib mentioned above.  My point was it would just help future developers to have those same 4 lines added in the official ripplelib.

**Comment by intelliot** [comment]
@kuyawa that’s a good idea. I think it might be even cleaner to expose the methods on `api` directly. Also, what do you think of https://github.com/ripple/ripple-lib/pull/830 ?

Want to contribute a PR? :)

**Comment by pftq** [comment]
That's the reason for the 4 lines I suggested (to expose it through the api
variable).

**Comment by kuyawa** [comment]
Regarding #830 "Add ability to derive address from secret" exposing the keypairs module would allow to manage keys easily depending on the needs. I agree on allowing to derive the publick key from the secret so we don't have to ask for both pieces of information, which is the issue I am facing right now as a wallet developer, so a simple api.keypairs.deriveKeypair(secret).publicKey would suffice.

We developers don't want to have our hands tied and we also hate loading two heavy libraries that practically do the same, as ripple-keypairs is already loaded in ripple-lib as webpack(33).

**Comment by movitto** [comment]
PR #923 opened which should resolve this issue.

**Comment by mDuo13** [comment]
This has been fixed in #932 and released in v1.1.0.
