### ISSUE TITLE
Can't find variable _

### ISSUE THREAD

**Issue by Julyyq** [ripple/ripple-lib#774]
I wanna use `ripple-lib` in the browser. I clone this project and run `npm install`, then run `gulp build-min` get the file `ripple-0.17.7-min.js`， but when I include this file in my html header, I got the following error:

![screenshot 2017-06-21 16 52 19](https://user-images.githubusercontent.com/2620575/27375663-7e072cbc-56a2-11e7-9b3a-7bf9295d3010.png)

BTW, any documentation on about how to use this library in browser? Thanks.

**Comment by sharafian** [comment]
If you're using ripple-lib in the browser, you need to include lodash first. Try adding:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.15.0/lodash.js"></script>
```

(Documentation on the lodash dependency is going to be added with this PR
https://github.com/ripple/ripple-dev-portal/pull/260 )

**Comment by Julyyq** [comment]
@sharafian Thanks, it works.
