### ISSUE TITLE
How to buy via API

### ISSUE THREAD

**Issue by fibo** [ripple/ripple-lib#784]
Hi, sorry for the newbie question, this subject is so interesting also from the point of view of a mathematician like me.

Can you please tell me if it is possible to buy XRP via API. I also do not understand reading docs where to get my address and my secret.
Is it necessary to build an exchange to buy and hold XRP directly? If yes what are the minimum actions necessary, how it works?

Thank you in advance.

**Comment by sublimator** [comment]
You can purchase fiat currency tokens/ious on the network at various
exchanges. Ripple has a builtin orderbook functionality, where people trade
various assets, including native XRP.

One such exchange: https://www.bitstamp.net/

**Comment by fibo** [comment]
Thank you very much for your answer.
I still not get if I purchase XRP from an exchange, do I own it? And what I get? I mean, do I get some token that represent what I bought?
And if I want to sell my XRP should I use an exchange again?

**Comment by sublimator** [comment]
At bitstamp you can deposit USD into their bank account, at which point you
can use the exchange to buy bitstamp XRP ious. You can then `deposit` into
the native ripple network, sending it to a ripple address (essentially a
public key), that matches a private key that you possess.

If you have the private key to make transactions utilizing those XRP you
can make a trade with anyone that is willing. That could be for another
gateway/exchange iou/token for some other fiat currency (e.g. JPY) or
perhaps someone would send you goods/services for a direct XRP payment.

To `own` XRP is to control the private key that enables transactions to
spend/utilize it on the native ripple network.

There's probably better places to get answers for the basics than
ripple-lib issues on Github :)

**Comment by fibo** [comment]
Thank you very much. I created an account on bitstamp and I will buy XRP. For other questions I will continue on the forum.

**Comment by sublimator** [comment]
No problem :)
