### ISSUE TITLE
How to deal with temREDUNDANT

### ISSUE THREAD

**Issue by afzydev** [ripple/ripple-lib#787]
When sender address and the destination address is same and I am using unique source tag and destination tag also for payments.

The transaction is showing invalid and showing message
> temREDUNDANT(Sends same currency to self.)

I am in a big trouble please tell me the way to deal with.

```
        var payment = {};
        payment.source = {};
        payment.source.address = inputData.sourceAddress;
        payment.source.maxAmount = {};
        payment.source.maxAmount.currency = inputData.sourceCurrency;
        payment.source.maxAmount.value = inputData.sourceValue;
        payment.source.tag=inputData.sourceTag;
        payment.destination = {};
        payment.destination.address = inputData.destinationAddress;
        payment.destination.amount = {};
        payment.destination.amount.currency = inputData.destinationCurrency;
        payment.destination.amount.value = inputData.destinationValue;
        payment.destination.tag=inputData.destinationTag;
```

Thanks

**Comment by tuloski** [comment]
Are you sending the same currency to the same address? If that is the case the temREDUNDANT is correct since the payment is actually doing nothing (self sending same currency).

**Comment by JoelKatz** [comment]
What is the reason for submitting the transaction exactly? The transaction has no paths. The source and destination currencies are the same. The transaction would have no effect on the ledger. You must control the source account to send the transaction, and both the source and destination accounts are the same. There would be no change to on ledger balances. If you want to send yourself a message without changing ledger balances, surely there are better ways to do it than submitting a payment transaction.

**Comment by afzydev** [comment]
@JoelKatz  
Thanks for your awesome suggestion.
One thing I am unable to use source and destination tags while preparing payment .
The code snippet is same as given above.

Thanks

Regards
Afzal

**Comment by JoelKatz** [comment]
@afzydev  I'm not sure I understand what you're asking.

**Comment by intelliot** [comment]
@afzydev If the source and destination currencies are the same, the sender address and the destination address must be different.

I'm closing this issue now, but feel free to let us know if you have further questions.
