### ISSUE TITLE
[docs] payment channel related transaction types not listed

### ISSUE THREAD

**Issue by michielbdejong** [ripple/ripple-lib#793]
https://ripple.com/build/rippleapi/#transaction-types does not list the payment channel related transaction types

cc @mDuo13

**Comment by FredKSchott** [comment]
This sounds like an API question/problem. [Move](https://github-issue-mover.appspot.com/) to https://github.com/ripple/rippled ?

**Comment by michielbdejong** [comment]
No, the file that needs editing is https://github.com/ripple/ripple-lib/blob/master/docs/src/transactions.md.ejs

**Comment by FredKSchott** [comment]
Oh! https://ripple.com/build/rippleapi/ docs are sourced out of ripple-lib? TIL

**Comment by michielbdejong** [comment]
I don't know that for sure, it may also be a duplicate copy. But yes, the file I want to see changed exists in this repo.

**Comment by mDuo13** [comment]
Yes, [they are](https://github.com/ripple/ripple-dev-portal/blob/master/dactyl-config.yml#L129).

**Comment by mDuo13** [comment]
This is (long since) done.
