### ISSUE TITLE
Feature request: support signing with ECDSA secp256k1 and Ed25519 private keys

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-lib#797]
Sign method should support signing with ECDSA secp256k1 and Ed25519 private keys (and not just with Ripple secret keys).

The format of these private keys needs to be documented.

**Comment by intelliot** [comment]
Thanks for submitting this issue. Could you elaborate on what the use case for this feature would be?

**Comment by matejr** [comment]
Easier generation of vanity addresses (account ids) with split-key mining, easier integration with hardware devices which store ECDSA private keys (it is not possible to use exported private key in any RippleAPI-based wallet), etc.

**Comment by intelliot** [comment]
This is now supported by specifying a `keypair` to the `sign` method. https://xrpl.org/rippleapi-reference.html#sign

With regards to the documentation of the format of the private keys, there's room for improvement. I'll open a new issue for that.
