### ISSUE TITLE
How to listen to events on the XRP Ledger (transaction, ledger, account) by a special account?

### ISSUE THREAD

**Issue by passionofvc** [ripple/ripple-lib#809]
I know subscribe ledger event with below code,
but how to listen to events on the XRP Ledger (transaction, ledger, account) by a special account?

```
api.connect().then( () => {
       console.log('Connection is open now.');
       return api.on('ledger', message => {
                 //console.log(message);
                 console.log(JSON.stringify(message, null, 2));
             }
        );
 });

```

**Comment by sharafian** [comment]
```js
const account = /* ... */
api.connect().then( () => {    
   api.connection.on('transaction', (ev) => {
      console.log(JSON.stringify(ev, null, 2))
   }) 
   return api.connection.request({
     command: 'subscribe',
     accounts: [ account ]
   })
})
```

This code allows you to listen for transactions on a given account. You can read more about the fields [here](https://ripple.com/build/rippled-apis/#subscribe)

**Comment by sublimator** [comment]
You guys survived ? :)

**Comment by passionofvc** [comment]
@sharafian 
thanks, if I have 1 million account,
whether I can subscribe account by 1 million or  should I call api.connection.request 
1 million time for one account?
I am sorry to be late.
```

const account = /* ... */
api.connect().then( () => {    
   api.connection.on('transaction', (ev) => {
      console.log(JSON.stringify(ev, null, 2))
   }) 
   return api.connection.request({
     command: 'subscribe',
     accounts: [ 1 million account ]
   })
})

```

**Comment by sharafian** [comment]
Yep, the `accounts` field can contain many account if you want to subscribe to more than one

**Comment by passionofvc** [comment]
@sharafian 
very thanks, I am newbie to javascript,
also learn many this time.

**Comment by mannutech** [comment]
This thing was not on their official documentation at all. 
Thanks for saving

**Comment by mannutech** [comment]
I figured it  out as per the latest build : 
```
client.connect().then((ok) => {
        client.connection._onMessage(JSON.stringify({
            type: 'transaction'
        }));
        client.connection.on('transaction', (EventBody) => {
            console.info('connected man');
        });
 return client.connection.request({
            command: 'subscribe',
            accounts: []
        })
})

````

Hope should work for you.

**Comment by intelliot** [comment]
In 1.0.0-beta.0 and later, [use the request() method directly (docs)](https://github.com/ripple/ripple-lib/blob/8833442b2bf8307e62b0944f188cdc7126f452df/docs/index.md#rippled-apis).

**Comment by tangnv** [comment]
Hi @intelliot, do we have any way to listening new ledger or new transaction?

**Comment by intelliot** [comment]
@tangnv Yes, use `api.request()` to subscribe to `ledger` for new ledgers, and `transactions` for new transactions. For transactions affecting a specific account, subscribe to `accounts` and use an array to specify the account(s) you're interested in. See [Listening to streams](https://developers.ripple.com/rippleapi-reference.html#listening-to-streams).

**Comment by dmitryrn** [comment]
@tangnv Hi, what if I need to listen new transactions for 1000000 accounts? If I will use `subscribe` with array of billion accounts than how it may affect performance or something else? Maybe I can break something at all? Are there any restrictions with it? Thanks you!

**Comment by tuloski** [comment]
> @tangnv Hi, what if I need to listen for new transactions for 1000000 accounts? If I will use `subscribe` with array of billion accounts than how it may affect performance or something else? Maybe it can break something at all? Are there any restrictions with it? Thanks you!

In that case it's better to just listen to all transactions.

**Comment by intelliot** [comment]
This is complete. Docs: https://xrpl.org/rippleapi-reference.html#listening-to-streams

**Comment by mmo2112** [comment]
> @tangnv Hi, what if I need to listen for new transactions for 1000000 accounts? If I will use `subscribe` with array of billion accounts than how it may affect performance or something else? Maybe it can break something at all? Are there any restrictions with it? Thanks you!

I think it's really not good cuz ripple may save list subscription of address on memory and will be dropped if ws connection is broken by undefined reason. Example on Btc, we have `importaddress` with option watch address and the physical node will storage those addresses in disk, so we can access them anytime, no need to worry about connection reset. Just imagine that we have 1 milliion ripple addresses and the connection is broken, we must re-subscribe those 1 milliion addresses or following traditional way is reading all transactions from every block, the hardest thing is speed of creating Ripple block too fast, so can be missed a lot of transactions or delay reading block. Please give me some advice, thanks so much.
