### ISSUE TITLE
RippledError(invalidTransaction)

### ISSUE THREAD

**Issue by thomsonimjd** [ripple/ripple-lib#817]
Below is my code for XRP transaction, I get invalid transaction error.  First I prepare the transaction and sign it and submit.  Could you  please let me know where I make mistake. 

I use the test net.

```
app.post('/rippleWithdrawAmount', (req, res)=>{
    const address = 'r3TeZ7jjRxJhKe3w2abYQoA8nU3t86LDwi';
    const payment = {
      "source": {
        "address": "r3TeZ7jjRxJhKe3w2abYQoA8nU3t86LDwi",
        "maxAmount": {
          "value": "0.01",
          "currency": "USD",
          "counterparty": "rKXwUaUXoBjbydksD8FCHSUiZa8B5JXZi5"
        }
      },
      "destination": {
        "address": "rPHtn8eJRXkt3meL1xc4up64SogDeVapxz",
        "amount": {
          "value": "0.01",
          "currency": "USD",
          "counterparty": "rKXwUaUXoBjbydksD8FCHSUiZa8B5JXZi5"
        }
      }
    };
      //preparing payement order.
      ripple_api.preparePayment(address, payment).then(prepared =>
      {
         console.info(JSON.stringify(prepared));
         const secret = 'snwUeaRH7XtL676rwugYXEVR7NrtC';
         const txJSON = JSON.stringify(prepared);

        //  signed transaction
         var signedPreparedTransaction = ripple_api.sign(txJSON, secret);
        //  console.info(JSON.stringify(signedPreparedTransaction));
        
         const signedTransaction = signedPreparedTransaction.signedTransaction;
        
         console.info(signedTransaction);
         //submitting payment order

         ripple_api.submit(signedTransaction)
         .then(result => {
             console.info("Successful in submitting payement: "+ result);
             res.json({"status":true, "hash":result});
         }).catch(err=>{
             console.error("Problem in submitting payement transaction: "+ err);
             res.json({"status":false, "error":err});
         });
      });
```

**Comment by intelliot** [comment]
@thomsonimjd Here are the issues I see:

1. The object returned by `preparePayment` includes a property called `txJSON` which you should pass to `sign`. In other words, you should replace this line:
```
const txJSON = JSON.stringify(prepared); // wrong
```
with:
```
const txJSON = prepared.txJSON; // use txJSON from preparePayment
```

2. When sending USD, you need to set up [trust lines](https://forum.ripple.com/viewtopic.php?t=3334) to the counterparty before making a payment.

To send XRP instead, you can use a payment such as:
```
  const payment = {
    "source": {
      "address": "r3TeZ7jjRxJhKe3w2abYQoA8nU3t86LDwi",
      "amount": {
        "value": "0.01",
        "currency": "XRP"
      }
    },
    "destination": {
      "address": "rPHtn8eJRXkt3meL1xc4up64SogDeVapxz",
      "minAmount": {
        "value": "0.01",
        "currency": "XRP"
      }
    }
  };
```
Notice that the currency is `XRP` and there is no counterparty.

3. You're missing one `});` at the end of your code :)

**Comment by crackcomm** [comment]
I can recommend checking out code of [ripple-node-examples](https://github.com/rippex/ripple-node-examples) or [ripple-wallet-cli](https://github.com/filidorwiese/ripple-wallet) to learn.

**Comment by intelliot** [comment]
@thomsonimjd Closing this issue now. Let us know if you have any other questions.

**Comment by thomsonimjd** [comment]
@intelliot It's working perfectly now, but the thing is I am not able to get transacion hash(tx) in return, I could get onlly status code and status message instead

**Comment by intelliot** [comment]
@thomsonimjd I'm not sure what you mean. If the problem persists, feel free to open a New Issue here on GitHub.

**Comment by thomsonimjd** [comment]
I have oppend a new issues #854 please see to that.

**Comment by intelliot** [comment]
The transaction hash is available _before_ you submit the transaction, in the `id` field returned by `sign`.
