### ISSUE TITLE
Failed payment preparation

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#819]
Hi all,
I did a script for payment, and I tried also the example in this repo for a payment and what I gen in the prepare payment is:

Connected...
[ValidationError(instance.payment.destination is not exactly one from < destinationExactAdjustment >,< minAdjustment >)]

I'm trying to send XRP, with the payment object as the following:
`const payment = {
  source: {
    address: address,
    maxAmount: {
      value: '0.01',
      currency: 'XRP'
    }
  },
  destination: {
    address: 'rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv',
    tag: 'tag',
    amount: {
      value: '0.01',
      currency: 'XRP'
    }
  }
};`

with IOUs it works fine, even with the destination TAG. I can't understand why it doesn't work with XRP.

**Comment by tuloski** [comment]
Ok, got it.
The destination tag has to be a number and not a string :)
But the error it returns is weird.

**Comment by intelliot** [comment]
Thanks for pointing this out. It would be good to improve that error message.

**Comment by junderw** [comment]
This is also caused if destination tag is outside the specified range:

`[0 - 4294967295]` (both sides inclusive)

Someone put in 8 billion as their tag and it threw this error.

**Comment by KasparTr** [comment]
Happy to fix this issue @intelliot. Will get on it if it works like this here (first time contributor here).

**Comment by lijianl** [comment]
> This is also caused if destination tag is outside the specified range:
> 
> `[0 - 4294967295]` (both sides inclusive)
> 
> Someone put in 8 billion as their tag and it threw this error.

what should i do if the tag is bigger than 4294967295

**Comment by junderw** [comment]
> > This is also caused if destination tag is outside the specified range:
> > `[0 - 4294967295]` (both sides inclusive)
> > Someone put in 8 billion as their tag and it threw this error.
> 
> what should i do if the tag is bigger than 4294967295

Throw your own custom, descriptive Error.

**Comment by lijianl** [comment]
> > > This is also caused if destination tag is outside the specified range:
> > > `[0 - 4294967295]` (both sides inclusive)
> > > Someone put in 8 billion as their tag and it threw this error.
> > 
> > 
> > what should i do if the tag is bigger than 4294967295
> 
> Throw your own custom, descriptive Error.



`{
  "source": {
    "address": "****",
    "maxAmount": {
      "value": "726.0346",
      "currency": "XRP"
    }
  },
  "destination": {
    "address": "*****",
    "amount": {
      "value": "726.0346",
      "currency": "XRP"
    },
    "tag": 8105548813
  }
}
{ ValidationError: instance.payment.destination is not exactly one from <destinationExactAdjustment>,<minAdjustment>


what shoud I do

**Comment by lijianl** [comment]
> > > This is also caused if destination tag is outside the specified range:
> > > `[0 - 4294967295]` (both sides inclusive)
> > > Someone put in 8 billion as their tag and it threw this error.
> > 
> > 
> > what should i do if the tag is bigger than 4294967295
> 
> Throw your own custom, descriptive Error.

how to send a Payment like this which with a big tag , C929299524DA98262B7C2FEAD621F1F935A92640F1310D5CD02632CA03837F2A;

the tag  is `DT: 895120383`

**Comment by intelliot** [comment]
@lijianl The [destination tag](https://xrpl.org/payment.html#payment-fields) is a `UInt32` which is a 32-bit unsigned integer. This means it has a maximum value of 4294967295. Therefore, a tag of 8105548813 is invalid.
