### ISSUE TITLE
getBalances() actNotFound

### ISSUE THREAD

**Issue by prinick96** [ripple/ripple-lib#821]
Hello, i have this:
```js
'use strict';
const RippleAPI = require('ripple-lib').RippleAPI;
var XRP = new RippleAPI({
    server: 'wss://s1.ripple.com' 
});

/**
 * Obtiene el balance de una wallet
 * 
 * @param {*} req 
 * @param {*} res 
 */
exports.getBalance = function(req, res) {
    var walletAddress = req.params.wallet;
    XRP.connect().then(() => {
        XRP.getBalances(walletAddress).then(balances => {
          console.log(JSON.stringify(balances, null, 2));
          process.exit();
        }).then(() => {
            return XRP.disconnect();
        }).catch(console.error);
    });
}
```
And i have this error:
![imagen](https://user-images.githubusercontent.com/11221009/34342192-ffa03db4-e986-11e7-8175-cf5d4642698f.png)

Any idea?

Thanks

**Comment by sharafian** [comment]
Can you also post the code that calls this function? What parameters are you passing in?

**Comment by prinick96** [comment]
I solved this, **actNotFound** error means when ipple account don't exists because don't are active with 20 XRP.

**Comment by webzorg** [comment]
My account is active but still I get actNotFound.

**Comment by intelliot** [comment]
@webzorg What is your account address? Are you on testnet or mainnet? Feel free to open an new issue with details.

**Comment by webzorg** [comment]
> @webzorg What is your account address? Are you on testnet or mainnet? Feel free to open an new issue with details.

resolved, node took time to get in sync or something like that
