### ISSUE TITLE
how to send many transactions

### ISSUE THREAD

**Issue by prinick96** [ripple/ripple-lib#822]
I need this.

Ripple account (A) send one transaction.
Ripple account (B) reciebe a % of this transaction.
Ripple account (C) reciebe another % of this transaction.

This is possible?

**Comment by sharafian** [comment]
Because Ripple is based around accounts instead of UTXOs (which allow several inputs and outputs), it's not possible to do that with one transaction. You can implement identical behavior by just submitting two separate transactions, though.

**Comment by prinick96** [comment]
Hello, thanks for help.
