### ISSUE TITLE
Compiled JS with Releases

### ISSUE THREAD

**Issue by pftq** [ripple/ripple-lib#824]
Can you attach the compiled full and min js files with each release? It is a bit cumbersome to set up node.js and github each time to get the latest ripplelib file.

**Comment by prinick96** [comment]
You only need NPM and:
```
npm install ripple-lib
```
Config your app, with Express by example and
```
npm run start
```
That's all

**Comment by pftq** [comment]
Right but for those who don't have a linux machine ready to go, it would be helpful to just have the already compiled JS files included in the release attachments.

**Comment by theogravity** [comment]
I think the OP meant for use within the context of a browser, not node.

**Comment by intelliot** [comment]
Here are the instructions for building a browser-compatible version of RippleAPI: https://ripple.com/build/rippleapi-beginners-guide/#build-instructions

@pftq Does this help?

I hesitate to include this with the releases because, as mentioned above, RippleAPI can also be used with node. We would be open to doing this (and calling out that it's a browser build) if there's demand for it, however.

**Comment by pftq** [comment]
It's not helpful to keep receiving instructions on compiling the build myself.  I am well aware of how to do so.  My request was to have it already included with the release of each version to save time for developers not using node.js

By not doing this, you are forcing a prerequisite right now of every developer wanting to use library having to also learn and set up a Linux machine, when having the JS file already compiled would open it to being used by any web developer using only Windows or Mac as well.

Similarly, casual users of your site that want to manually check on their own right now if you are using the official Ripplelib js file have no way of doing so without also setting up an entire Linux environment.

It is one extra step for RL who already has the linux setup to also compile and include the JS file in the release, vs requiring every user thereafter to also set up and compile.

**Comment by intelliot** [comment]
@pftq Thanks for clarifying. Actually, there is no need to set up or use a Linux machine; Node.js is available for Windows and Mac. I actually build ripple-lib on a Mac.

Still, this is a good idea. I'll build the library and upload it shortly. Thank you for the suggestion!

**Comment by pftq** [comment]
Thank you - you are correct that node.js can be compiled on Windows, but I think you get the point that it would make the library friendly to a wider audience of web developers.

**Comment by intelliot** [comment]
The [0.17.9 release](https://github.com/ripple/ripple-lib/releases/tag/0.17.9) has been updated with the built JS files, and the SHA checksums for these files can be viewed in the [changelog](https://github.com/ripple/ripple-lib/blob/develop/HISTORY.md).

How does this look?

**Comment by pftq** [comment]
Great - that's perfect, thanks.  This will be very helpful.
