### ISSUE TITLE
getFee, withdraw or deposit

### ISSUE THREAD

**Issue by Jacobth** [ripple/ripple-lib#838]
The getFee() method return the estimated fee for a transaction in ripple. But is this the fee for a withdraw or a deposit or both? Also is this the fee for withdraw/deposit ETH aswell?

**Comment by intelliot** [comment]
This is the fee for any transaction on the XRP Ledger. However, I would recommend testing with different fee levels because it's usually not necessary to pay this fee if you are willing to wait a little longer.

Does that answer your questions?

**Comment by Jacobth** [comment]
Thank you, it does!
