### ISSUE TITLE
tefPAST_SEQ

### ISSUE THREAD

**Issue by tuloski** [ripple/ripple-lib#848]
Hi,
sometimes the API, after it's connected for a while (days?) returns tefPAST_SEQ on all transactions.
My rippled was synced with the network since other API instances were working well. It seems like it fails to get the last sequence number.
I don't know how I can debug and reproduce it to help understanding the cause. If you have any idea I can test.

**Comment by intelliot** [comment]
1. Get the next sequence number for the account (perhaps use `getAccountInfo()` for this)
2. Look at the sequence number used for the transaction that failed (perhaps look at the `Sequence` property)

Alternatively, could you share a test script that reproduces the issue? You can email it to me directly if it's too large to share here.

**Comment by tuloski** [comment]
Ok, I'm trying to get the sequence of the transaction and of the account. I'll try that before sending scripts to test.

**Comment by intelliot** [comment]
Thanks. I actually think that the most reliable way to send transactions is to track sequence numbers yourself. Then if you get tefPAST_SEQ, you know that either your account has been compromised, or your app logic is wrong - both situations that require manual intervention.

Closing this issue, but please feel free to open a new one if the problem persists.
