### ISSUE TITLE
Not able to get tx hash after sending xrp

### ISSUE THREAD

**Issue by thomsonimjd** [ripple/ripple-lib#854]
`router.post('/sendRipple', (req, res)=>{
    
    var fromAddress = req.body._fromAddress;
    var toAddress = req.body._toAddress;
    var balance = req.body._balance;
    var secret = req.body._privatekey;

    console.info('fromAddress: '+fromAddress);
    console.info('toAddress: '+toAddress);
    console.info('balance: '+balance);    
    console.info('secret: '+secret);
    
        // const address = 'r3TeZ7jjRxJhKe3w2abYQoA8nU3t86LDwi';
        const address = fromAddress;
        
        const payment = {
            source: {
              address: fromAddress,
              maxAmount: {
                value: balance,
                currency: 'XRP'
              }
            },
            destination: {
              address: toAddress,
              amount: {
                value: balance,
                currency: 'XRP'
              }
            }
          };
          //preparing payement order.
          ripple_api.preparePayment(address, payment).then(prepared =>
          {
             console.info(JSON.stringify(prepared));
            //  const secret = 'snwUeaRH7XtL676rwugYXEVR7NrtC';
            //  const txJSON = JSON.stringify(prepared);
    
            //  signed transaction
             var signedPreparedTransaction = ripple_api.sign(prepared.txJSON, secret);
            //  console.info(JSON.stringify(signedPreparedTransaction));
            
             const signedTransaction = signedPreparedTransaction.signedTransaction;
            
             console.info(signedTransaction);
             //submitting payment order
    
             ripple_api.submit(signedTransaction)
             .then(result => {
                 console.info("Successful in submitting payement: "+ result);
                 res.json({"status":true, "hash":result});
             }).catch(err=>{
                 console.error("Problem in submitting payement transaction: "+ err);
                 res.json({"status":false, "error":err, "msg":"submitting payment"});
             });
          }).catch(err=>{
            console.error("Problem in preparing payement transaction: "+ err);
            res.json({"status":false, "error":err, "msg":"preparing payment"});
          });
    });`

Above is my nodejs code to send ripple to other ripple accounts, which works perfectly but in return I should be able to get an transaction hash to check about the transaciton that has been done, but instead I get a string saying `"The transaction was applied. Only final in a validated ledger."`.  And also could you please let me know if there is any testnet ripple explorer to check about address and transaction hash like koven.etherscan.io(ether).

**Comment by sharafian** [comment]
The transaction hash can be found in `signedPreparedTransaction.id`

**Comment by intelliot** [comment]
In other words, the transaction hash is available _before_ you submit the transaction, in the `id` field returned by `sign`.
