### ISSUE TITLE
ValidationError in getTransactions

### ISSUE THREAD

**Issue by N3TC4T** [ripple/ripple-lib#855]
Getting transactions for specific account works find without "start" option but after including the "start" param I'm getting below error :

`instance.options is of prohibited type [object Object]`

-----------------------------------------------------------------

Works Fine :

`{minLedgerVersion: 5978794, maxLedgerVersion: 6963598, limit: 5}`

Getting Error : 
`
{minLedgerVersion: 5978794, maxLedgerVersion: 6963599, limit: 5, start: "0CD33DF995C6545038F58EB65F46671D0C3BCD2288EEF1CF350F597A3C5F110F"}`

Also tried to include other options and almost tried everything but can't figure out where is the problem .

Regards

**Comment by intelliot** [comment]
`start` cannot be used in conjunction with `minLedgerVersion` or `maxLedgerVersion`. The schema rule for this can be found here:

https://github.com/ripple/ripple-lib/blob/ca74cf1/src/common/schemas/input/get-transactions.json#L58-L63

**Comment by N3TC4T** [comment]
That's works fine after removing 'minLedgerVersion' and 'maxLedgerVersion' when I include 'start' .

Thanks @intelliot .

**Comment by webtech2412** [comment]
I am facing the same issue, i have set up full node on my server. Everything is working but getTansactions is throwing error error - error [ValidationError(instance.options.maxLedgerVersion is not exactly one from [subschema 0],[subschema 1])]

I tried passing "minLedgerVersion" from my getserverinfo function using the completeLedger values but it is not working and giving MissingLedgerHistoryError(Server is missing ledger history in the specified range)]

I observe completeLedger is giving me random values. I tried to split and use min/max ledger version but that is not working as the format is getting changed
Somitime it give like this
completeLedger ="54873243-54888233,54888334-54888352,54888587-54888604,54888706-54888755,54888921-54888922,54889023-54889061,54889170-54889190,54889347-54889402,54889506-54889562,54889665-54889950,54890141-54890169,54890448-54890460,54890561-54890582,54890694-54890732,54890868-54891060,54891231-54898249"

and some time "completeLedgers": "54873243-54888233,54888334",

How i can resolved this. getTransactions is supposed to work with address only and options are optional but it is not working. Please help.
