### ISSUE TITLE
TypeScript declaration files are generated for browser build

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#862]
The browser build of ripple-lib is also getting TS declaration files in `./build/dist/npm/`. We don't want this, right?

**Comment by FredKSchott** [comment]
Huh, that's weird. It looks like webpack tries to follow your tsconfig file, so it thinks it should also generate type definitions. 

I'm not sure if there's a way to get these definitions working with a source map, lets just disable for now.  PR here: https://github.com/ripple/ripple-lib/pull/864
