### ISSUE TITLE
Payment type is not conforming to validation schema

### ISSUE THREAD

**Issue by darkmemo** [ripple/ripple-lib#866]
`Payment` type is defined as (https://github.com/ripple/ripple-lib/blob/develop/src/transaction/payment.ts)

```ts
 export type Payment = {
   source: Adjustment & MaxAdjustment,
   destination: Adjustment & MinAdjustment,
  [...]
```

`source-adjustment.json` and `destination-adjustment.json` schemas are defined as;

```js
// source-adjustment.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "sourceAdjustment",
  "type": "object",
  "oneOf": [
    {"$ref": "sourceExactAdjustment"},
    {"$ref": "maxAdjustment"}
  ]
}

// destination-adjustment.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "destinationAdjustment",
  "type": "object",
  "oneOf": [
    {"$ref": "destinationExactAdjustment"},
    {"$ref": "minAdjustment"}
  ]
}
```

When payment object is created like;

```ts
const source = {
  address: fromAddress, 
  amount: {value: "", currency: ""}, 
  maxAmount: {value: amount, currency: "XRP"}
};
const destination = {
  address: toAddress, 
  amount: {value: amount, currency: "XRP"}, 
  minAmount: {value: "", currency: ""}
};
const payment = {source, destination};
```

validation fails with:
> ValidationError: instance.payment.source is not exactly one from \<sourceExactAdjustment>,\<maxAdjustment>,instance.payment.destination is not exactly one from \<destinationExactAdjustment>,\<minAdjustment>

This failure is reasonable due to schema, since it requires _one of_ `sourceExactAdjustment` and `maxAdjustment` etc.

When payment is created using one of adjustment for source and destination;

```ts
const source = {
  address: fromAddress, 
  maxAmount: {value: amount, currency: "XRP"}
};
const destination = {
  address: toAddress, 
  amount: {value: amount, currency: "XRP"},
};
const payment = {source, destination};
```

then typescript compiler fails with 

```
error TS2345: Argument of type '{ source: { address: string; maxAmount: { value: string; currency: string; }; }; destination: { a...' is not assignable to parameter of type 'Payment'.
  Types of property 'source' are incompatible.
    Type '{ address: string; maxAmount: { value: string; currency: string; }; }' is not assignable to type 'Adjustment & MaxAdjustment'.
      Type '{ address: string; maxAmount: { value: string; currency: string; }; }' is not assignable to type 'Adjustment'.
        Property 'amount' is missing in type '{ address: string; maxAmount: { value: string; currency: string; }; }'.
```

Typescript compiler fails since it expects source and destination to be **intersection** of two types;

```ts
   source: Adjustment & MaxAdjustment,
   destination: Adjustment & MinAdjustment,
```

but according to schema, they should be **union** of them;

```ts
   source: Adjustment | MaxAdjustment,
   destination: Adjustment | MinAdjustment,
```

Is this an intentional difference between `Payment` type and schema? Or am I missing something here?

**Comment by darkmemo** [comment]
Before typescript conversion, it seems source and destination were union types;

https://github.com/ripple/ripple-lib/blob/5979ff6197252be89ae56532537fd7b62f831080/src/transaction/payment.js#L14-L16

**Comment by sublimator** [comment]
Looks like a mistake and should be a union ( OR )  indeed

Is the test suite not converted to TypeScript yet?

**Comment by sublimator** [comment]
Hrmmmm, seems not

**Comment by FredKSchott** [comment]
Ah, yes this looks like a mistake made during the TS conversion. @darkmemo any interest in creating a PR to change `&` to `|`?

**Comment by darkmemo** [comment]
@FredKSchott: sure.
