### ISSUE TITLE
How to get all created accounts of my rippled without DATA api?

### ISSUE THREAD

**Issue by JJNET** [ripple/ripple-lib#874]
I can't find RippleAPI to get all accounts created by my rippled of server.

How can I get all accounts created by function "generateAddress" of RippleAPI?

If impossible, Can I dynamically add account for subscribing & unsubscribing?

It is very important to manage huge accounts of crypto exchange in order to operate without suspension or shutdown websocket subscribing server.

cf)
I wrote this code to subscribe multi account's transaction, and it is well doing now.
(All accounts is testnet addresses.)

const RippleAPI = require('ripple-lib').RippleAPI
const api = new RippleAPI({
    server: 'ws://localhost:6006' // Private rippled server 
});

api.on('error', (errorCode, errorMessage, data) => {
    console.log(errorCode + ': ' + errorMessage);
});

api.on('connected', () => {
    console.log('Connection is open now.');
});

//const account = 'rEsxttdiVe9Ps8taKqMBUcMsq7QcUfMhtq'
api.connect().then( () => {
   api.connection.on('transaction', (ev) => { 
      var txhash = JSON.stringify(ev["transaction"]["hash"], null, 2)
      var valida = JSON.stringify(ev["validated"], null, 2)
      txhash = txhash.replace(/\"/gi, '')
      if(valida == "true" ) {
        console.log(txhash)
      }
   })
   return api.connection.request({
     command: 'subscribe',
     accounts: [ 'rEsxttdiVe9Ps8taKqMBUcMsq7QcUfMhtq',
                 'rJRRYqUGdtCxPBnio6zzHY4BRok9kqSoVD',
                 'rpSZeSoudR3qGTKEezvZxEqrsjEYcxEy3T',
                 'rMcHxejVWj6nRWMxuBCWGXzeafsvEAYsGT' ]
   })
})

**Comment by JJNET** [comment]
Hi @intelliot 

I know that. And I know DATA api can do it. by https://ripple.com/build/data-api-v2/#get-accounts
(But, It doesn't support RippleAPI maybe.)

So I have a plan to solve this problem.

If Node.js server receive "generateAddress" command via client, 
then I call  'subscribe' command at the same time.

But, I don't know it is possible or not. Because one side of forked daemon have to subscribe transaction from rippled and the other side have to wait client command to register address for subscribe.

**Comment by JJNET** [comment]
@intelliot

And I surprised that Exchanges typically use 1 or 2 hot/cold accounts. Really?
Bitcoin or Ethereum use as much as members' counts.

**Comment by JJNET** [comment]
Hi @intelliot

I just put the program into the concept as I said above and just tested it. It works well.
But there's a fatal problem. If I stop Node.js daemon, All addressed accounts was lost.

It looks like registered subscribe accounts are managed by Node.js other than rippled itself.

**Comment by intelliot** [comment]
@JJNET Correct - the XRP Ledger uses an account-based ledger, different from Bitcoin/Ethereum. Each account has reserve requirements (currently 20 XRP), making it cost-prohibitive to create an account for each member. Instead, a few accounts will suffice.

No, the destination tag is not the address. You can read more about destination tags here:

- https://ripple.com/build/gateway-guide/#source-and-destination-tags
- https://forum.ripple.com/viewtopic.php?f=1&t=3068

The subscribed accounts are specific to your websocket connection with rippled. These are not persisted, so you should store them yourself, in your own database or other persistent storage.

**Comment by intelliot** [comment]
Since subscriptions are specific to one websocket connection instance, they are not persisted after the websocket is closed or disconnected. You'll need to have your own persistent storage to keep track of the accounts you care about. I'm closing this issue, but feel free to open a new one if you have additional questions. Thanks!
