### ISSUE TITLE
Unable to get address balance using api.getBalances

### ISSUE THREAD

**Issue by zeshanvirk** [ripple/ripple-lib#878]
i generated an address using **api.generateAddress()** and then i pasted that address in getAddressbalances method like

**const address = 'rsX9LUYW217P2HgNXKMwwThPzpqhajahZ7';**

 api.getBalances(**address**).then(**balances** =>
        {
            console.log(**balances**);
        });

but i got this error print on console 
**(node:1260) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): **[RippledError(actNotFound)]**
**
i'm using Public rippled server hosted by Ripple, Inc.

 **server: 'wss://s1.ripple.com'** 

then i generate a testnet address from [https://ripple.com/build/xrp-test-net/](url) and pasted that address and i got same error. but when i use the address that is given in **getBalances** **example** it gave me **response**. Same in case of **api.getAccountInfo** Whats the issue?

**Comment by intelliot** [comment]
Hi @zeshanvirk -

The XRP Ledger has an entry for each account that has been activated (created). When you generate an address, the account has not yet been activated. It's only secret/address pair on your local machine.

To activate the account on the XRP Ledger, you need to send at least 20 XRP to the address. Sending 20 or more XRP to the address will automatically activate it.

XRP Test Net addresses should only be used on the test net. As you can see on https://ripple.com/build/xrp-test-net/, Ripple offers a test net server that you can connect to via websockets: `wss://s.altnet.rippletest.net:51233`. If you connect to this server and call `getBalances` with an address that has been activated with Test Net XRP, then you'll get a successful response.
