### ISSUE TITLE
getTransactions error

### ISSUE THREAD

**Issue by zeshanvirk** [ripple/ripple-lib#879]
Trying this code to get list of transactions but getting the error: 
```
 api.connect().then(() => {
  const address = 'r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59';
  api.getTransactions(address).then(transaction => {
    console.log(transaction);
  });
});
```

**UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [MissingLedgerHistoryError(Server is missing ledger history in the specified range)]**

**Comment by intelliot** [comment]
Hi @zeshanvirk -

This error means that the rippled server doesn't have full ledger history. Which rippled server are you connected to?

Here are some ways to address the issue:

If you only need to get transactions within a certain range, use `getServerInfo()` and look at the `completeLedgers` field. Ensure that you're getting transactions for a range that the server has. For example, if you see:
```
"completeLedgers": "36294002-37603312"
```

Then you can query for transactions within that range:
```
api.getTransactions(address, {
        minLedgerVersion: 36542093,
        maxLedgerVersion: 37603306
    }).then(transaction => {
        console.log(transaction);
    });
```

If the server doesn't have the ledgers you need, you'll need to configure rippled to store more history. You may also need to wait for the server to fetch the ledgers needed.

If you really need *all* transactions, you should query a full-history server. You can configure your own server this way. Ripple also runs one.

Does this help?

**Comment by intelliot** [comment]
@zeshanvirk I'm closing this issue, but please let us know if you'd like more assistance.

**Comment by zeshanvirk** [comment]
i'm using ripple public server, s2.ripple.com

**Comment by fsanano** [comment]
I also catch this bug, but when I add minLedgerVersion and maxLedgerVersion from api.getServerInfo(), catch another error:

```
ValidationError: instance.options.minLedgerVersion is not exactly one from [subschema 0],[subschema 1],instance.options.maxLedgerVersion is not exactly one from [subschema 0],[subschema 1]
```
I use testnetwork wss://s.altnet.rippletest.net:51233
But I adjusted it to the touch. Change the minLedgerVersion and maxLedgerVersion type from String to Number.
And I'm writing this so others can solve this problem faster.
And the request to the developers to change the error response in this case.
Thank you!

**Comment by zeshanvirk** [comment]
Share the code that works for you

**Comment by fsanano** [comment]
```
async rippleFetchWalletTransactions(address) {
  try {
    await api.connect();
    const serverInfo = await api.getServerInfo();
    const ledgers = serverInfo.completeLedgers.split('-');
    const minLedgerVersion = Number(ledgers[0]);
    const maxLedgerVersion = Number(ledgers[1]);

    const transactions = await api.getTransactions(address, {
      minLedgerVersion,
      maxLedgerVersion,
    });
    console.info('transactions', transactions);

    await api.disconnect();
  } catch (e) {
    console.error('e', e);// eslint-disable-line
  }
},
```

**Comment by princesinha19** [comment]
@fsanano It's not working for me.

**Comment by intelliot** [comment]
@princesinha19 If the error persists, create a [New issue](https://github.com/ripple/ripple-lib/issues/new) and include a code sample.
