### ISSUE TITLE
MissingLedgerHistory

### ISSUE THREAD

**Issue by zeshanvirk** [ripple/ripple-lib#890]
I'm using ripple testnet server wss://s.altnet.rippletest.net:51233  and when i try to get allTransactions against an address i got MissingLedgerHistoryError. When i try to get a transaction by id, i got it successfully. Whats the issue?

**Comment by tuloski** [comment]
By allTransactions you mean using getTransactions?

**Comment by zeshanvirk** [comment]
yes.

**Comment by intelliot** [comment]
Hi @zeshanvirk -

The testnet server does not have full history. You can use `getServerInfo()` and look at `completeLedgers` to see how much history is available. When using `getTransactions`, use `minLedgerVersion` and `maxLedgerVersion` to specify the range of ledgers to get transactions from.

```
// TODO: Set `minLedgerVersion` and `maxLedgerVersion`
const options = {
  minLedgerVersion: ...
  maxLedgerVersion: ...
}

api.getTransactions(address, options).then(data => {
  // ...
})
```
