### ISSUE TITLE
When concurrency is used for more than 100 times, API will report "websocket was closed"

### ISSUE THREAD

**Issue by LuoRyan** [ripple/ripple-lib#903]
> //************************************************************//
errors:
Q1.when concurrent users increase(maybe 100users/s),I recevied many errors from RippleAPI  instance,like this:

>2018-05-27T17:03:33.059||server=iZ8vb448nfpi49cy9g56g3Z||pid=23947||level=ERROR||reqid=getLedger(38952669)||
wsreqid=e2c60d6fcd9c48dbad8be0f5cb71a9c6||onUpdateBlockError||code=||message=websocket was closed||stack=[DisconnectedError(websocket was closed)]
at WebSocket.onDisconnect (/data/wallet/xrp/node_modules/ripple-lib/dist/npm/common/connection.js:370:24)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:131:20)
at WebSocket.emit (events.js:214:7)
at WebSocket.emitClose (/data/wallet/xrp/node_modules/ripple-lib/node_modules/ws/lib/WebSocket.js:211:10)
at _receiver.cleanup (/data/wallet/xrp/node_modules/ripple-lib/node_modules/ws/lib/WebSocket.js:199:39)
at Receiver.cleanup (/data/wallet/xrp/node_modules/ripple-lib/node_modules/ws/lib/Receiver.js:520:15)
at WebSocket.finalize (/data/wallet/xrp/node_modules/ripple-lib/node_modules/ws/lib/WebSocket.js:199:20)
at emitNone (events.js:111:20)
at Socket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)

>//************************************************************//
Q2.When I received to much errors, The node.js process eats a lot of memory,like this:
│App name    │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user  │ watching │
│ xrp_server   │ 0  │ fork    │ 23947 │ online │ 3       │ 25m    │ 1%  │ 1.7 GB   │ admin │ disabled │

So, can you help me to see it? Thank you

**Comment by LuoRyan** [comment]
@intelliot 
Can you help me to see it? Thank you

**Comment by intelliot** [comment]
What rippled server are you using? Are you running rippled yourself? If the server disconnects you, you’ll get that error.

**Comment by LuoRyan** [comment]
yes, I run the rippled server locally(should be Stock server mode).The rippled.cfg is:
`[server]
port_rpc_admin_local
port_peer
port_ws_admin_local
#port_ws_public
#ssl_key = /etc/ssl/private/server.key
#ssl_cert = /etc/ssl/certs/server.crt

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 127.0.0.1
protocol = http

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[port_ws_admin_local]
port = 6006
ip = 0.0.0.0
admin = 127.0.0.1
protocol = ws

[node_size]
medium

[node_db]
type=RocksDB
path=/var/lib/rippled/db/rocksdb
open_files=2000
filter_bits=12
cache_mb=256
file_size_mb=8
file_size_mult=2
online_delete=20000000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command" : "server_info" }
{ "command": "log_level", "severity": "debug" }

[ssl_verify]
1

[shard_db]
type=NuDB
path=/data/xrp/nudb
max_size_gb=800

[ledger_history]
5000`

**Comment by intelliot** [comment]
I recommend using a single connection to rippled, no matter how many users your site has. There’s no need to disconnect.

**Comment by LuoRyan** [comment]
@intelliot 
OK，I will use a single connection to rippled, thanks~~

I see this info at: https://developers.ripple.com/rippled-server-modes.html#properties-of-a-good-validator
`Stock server - follows the network with a local copy of the ledger.`
`Validating server, or validator for short - participates in consensus.`

As an exchange, we need history ledger data and sumbit payment.(At present, the Stock server mode we use)
In this case, which rippled server mode should we choose?
Can you give me some advice?

**Comment by intelliot** [comment]
Stock server is the correct mode to use.

**Comment by LuoRyan** [comment]
@intelliot
Thank you very much~~~

**Comment by LuoRyan** [comment]
@intelliot 
Do you know how to configure the rippled server to get historical ledger?(I got this error from my local rippled server "Server is missing ledger history in the specified range")
I use these commands, but there is no historical ledger in the server_info result.

`
rippled ledger_cleaner 38996182
rippled ledger_request 38996182
`
server_info:
`
{
    "result": {
        "info": {
            "build_version": "1.0.0",
            "complete_ledgers": "38996184-38997236",
            "hostid": "MATH",
            "io_latency_ms": 1,
            "jq_trans_overflow": "0",
            "last_close": {
                "converge_time_s": 3,
                "proposers": 16
            },
`

**Comment by LuoRyan** [comment]
@intelliot 
Can you help me to see it? Thank you
topo: AppUsers --->[http]--->koa2Server --->[one instance of RippleAPI]---->RippledServer(local)
**When a concurrent request is more than 100+, a request Hang up occurs for 446160ms**
code:
`let Remote                    = require("ripple-lib").RippleAPI;
let remote                    = new Remote({"ws://10.200.173.54:6006/",  6*1000,});
`

`async **function** request(parameter, method, ...options) {

        const start   = Date.now();
        const wsreqid = utilImp.get32UUIDString();
        let reqTrace  = {
            reqid:   parameter.reqid,
            wsreqid,
            method,
            options: JSON.stringify(options || null),
            msg:     "WebSocket request begin...",
        };

        logger.info(reqTrace);

        let result   = await remote.connect().then(async () => {
            logger.info({reqid: parameter.reqid, wsreqid, method, msg: "method begin>>>>"});
            let res = await remote[method](...options);
            logger.info({reqid: parameter.reqid, wsreqid, method, msg: "method ended<<<<"});
            return res;
        }).catch(err => {
            let {code, subCode} = errImp.getWebsocketErrorCode(err);
            if (err) err.reqid = `${parameter.reqid}||wsreqid=${wsreqid}||onWebSocketError()`;
            return errImp.getExceptionData(code, subCode, err);
        });
        const ms     = Date.now() - start;
        let resTrace = {
            reqid: parameter.reqid,
            wsreqid,
            method,
            body:  JSON.stringify(result),
            cost:  `${ms}ms`,
            msg:   "WebSocket request end.",
        };
        logger.info(resTrace);
        return result;
    }`

logs:

>2018-06-05T15:54:04.830||method=getBalances||options=["rf1GcLkC5UojaoWcfa1GZGbp9fT8L8vZLH"]||msg=WebSocket request begin...
>**2018-06-05T15:54:04.994**||method=getBalances||msg=method begin>>>>
>2018-06-05T16:01:30.852||onWebSocketError()||code=||message=websocket was closed
>**2018-06-05T16:01:30.990**||method=getBalances||body={}||cost=446160ms||msg=WebSocket request end

**Comment by LuoRyan** [comment]
@intelliot 
Is it possible that the websocket connection caused a memory leak?

**Comment by intelliot** [comment]
It’s possible, but I don’t see evidence of a memory leak. Where do you see that?

**Comment by intelliot** [comment]
@LuoRyan I'm closing this issue, but please let us know if you spot a memory leak.
