### ISSUE TITLE
Create signedTransaciton locally

### ISSUE THREAD

**Issue by yoyoyousei** [ripple/ripple-lib#905]
Is there any method to create signedTransaction locally?

I want to create signed transaction without connection with ripple server.
like:
```
api.preparePayment(address, payment)
    .then(prepared => {
        const signRes = api.sign(prepared.txJSON, secret);
    }).catch(fail);
```

I already succeeded to create and send a signed transaction like the following snippet:
```
api.connect().then(()=>{
     console.log('connected...');
     return api.preparePayment(address, payment, instructions).then(prepared => {
         console.log('Payment transaction prepared....');
        
         const signRes = api.sign(prepared.txJSON, secret);
         console.log('Payment transaction signed....');
         const txHash = signRes.id;
         console.log(`txhash: ${txHash}`);
         api.submit(signRes.signedTransaction).then(quit, fail);
     });
 }).catch(fail);
```

**Comment by intelliot** [comment]
Yes. The sign() method works without a connection to a ripple server. You need to provide all of the transaction instructions like the sequence number, fee, etc.

**Comment by yoyoyousei** [comment]
I understood preparePayment() need to connect internet to correct information of ripple network.
So if I correct information(like fee, etc) beforehand, no need to connect internet in signing.

I succeed to sign transaction like this snippet: 
```
const txJSON = '{"Flags":2147483648,"TransactionType":"AccountSet","Account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","Domain":"726970706C652E636F6D","LastLedgerSequence":8820051,"Fee":"12","Sequence":23}';
var r = api.sign(txJSON, secret);
```

Thank you for your advice, @intelliot !

**Comment by intelliot** [comment]
@yoyoyousei Cool - that works. Note that writing txJSON that way requires using the rippled API's transaction format. The `preparePayment()` and most other `prepare*` methods can be used offline if you specify the `fee`, `sequence`, and `maxLedgerVersion` parameters. See [Offline functionality](https://developers.ripple.com/rippleapi-reference.html#offline-functionality).

**Comment by yoyoyousei** [comment]
@intelliot wow. So if `fee`, `sequence` and `maxLedgerVersion` are specified in `instructions`, txJson is generated in offline.
Thank you for additional information!

**Comment by yoyoyousei** [comment]
@intelliot As you said,  I succeeded to get txJson in offline when I specified fee, sequence and maxLedgerVersion in instructions.

But, Because I want to create client-side ripple wallet, I want to get txJson not wrapped  by Promise.
Can ripple-lib expose (createPaymentTransaction)[https://github.com/ripple/ripple-lib/blob/develop/src/transaction/payment.ts] method?
