### ISSUE TITLE
ValidationError(xrpToDrops: value '19792.80964382' has too many decimal places.)

### ISSUE THREAD

**Issue by jnr101** [ripple/ripple-lib#906]
Hi,

just testing the 1.0.0-beta.2 and find the following 'breaking' change:

```
{
  "direction": "sell",
  "quantity": {
    "currency": "BCH",
    "counterparty": "rcyS4CeCZVYvTiKcxj6Sx32ibKwcDHLds",
    "value": "10.42696400"
  },
  "totalPrice": {
    "currency": "XRP",
    "value": "19792.80964382"
  }
}

[09/06/2018 21:47:20] Error: [ValidationError(xrpToDrops: value '19792.80964382' has too many decimal places.)]
```

It [seems](https://github.com/ripple/ripple-lib/blob/1aa9feda715f792aa333d77e2ae577bb98191f3d/src/common/utils.ts#L81) the maximum is 6 decimals, which makes sense as that is the amount that leads to drops.
I can round it up in my own code to 6 decimals, but have you considered doing this in ripple-lib? I'm ok either way and will fix it in my code, but it is a breaking change (found out just in time :-))

**Comment by intelliot** [comment]
Good catch. Do you read our release notes in HISTORY.md? This was mentioned under the `1.0.0-beta.1 (2018-05-24)` release. 

Rounding is a nice idea though. Let me try how that change looks.

**Comment by jnr101** [comment]
Hi intelliot, you are correct, sorry, it has been described there as breaking change. I glanced over it at the time and after testing the code to find that things still worked ok after upgrade to `1.0.0-beta.1`. Strange enough the breaking effect seems to have gone live somehow after upgrading to version `1.0.0-beta.2`.

- _pro_ rounding in ripple-lib: calculations using dividing/multiply is very common, always leading to many decimals behind the point. In my case I have been a bit sloppy and use an arbitrary rounding of 8 digits for both XRP and non-XRP currencies, 8 digits to be on the save side just in case the traded assets are largely different in value.
- _con_ rounding in ripple-lib: It is less formal/clear how ripple-lib behaves. It is better to have the developer know exactly what he is/should be doing

**Comment by intelliot** [comment]
How do you do the rounding?

We could simply truncate the value to 6 decimal places (which is what we did before 1.0.0-beta.1) or we could round up if it's at least halfway to the next drop (0.5 drops or higher).

Or, of course, we leave it as-is and not round.

**Comment by jnr101** [comment]
I round up if at least halfway to the next drop (0.5 drops or higher).  Come to think of it, that's exactly the arbitrary thing about it. If you leave it as-is then the api-user must decide for himself, so maybe that is the best thing to do in this case ..

**Comment by intelliot** [comment]
That makes sense. Thanks for opening the issue, and do let us know if you have other suggestions for improvements.
