### ISSUE TITLE
Activation of Account

### ISSUE THREAD

**Issue by yoyoyousei** [ripple/ripple-lib#910]
I have some question about account activation.
I know here is not best place to question about specifications of ripple, but I couldn't get any response from ripple customer support...

My question is: 
1. What is the difference between activated account and unactivated account?
2. What happen if the balance of my ripple account which once activated belows 20XRP?
3. Do XRP disappear when 10 XRP sent to inactivated account?

Any comments and advices are appreciated.

**Comment by wilsonianb** [comment]
hi @yoyoyousei 
This page has information relevant to your question:
https://developers.ripple.com/reserves.html

Regarding 3, the transaction will fail with `tecNO_DST_INSUF_XRP`. You would pay the fee you specified in the transaction but would keep the 10 XRP.
https://developers.ripple.com/tec-codes.html

**Comment by intelliot** [comment]
1. An account becomes activated when it receives its first payment, and the payment must deliver at least the base reserve (currently 20 XRP).
2. "When an address holds less XRP than its current reserve requirement, it cannot send new transactions that would transfer XRP to others, or increase its own reserve." [(Source)](https://developers.ripple.com/reserves.html)
3. No.

Hope this helps! Let us know if you have additional questions.
