### ISSUE TITLE
fee format when using maxFee

### ISSUE THREAD

**Issue by elmurci** [ripple/ripple-lib#911]
Not sure if this is actually a bug as the field `maxFee` in the Transaction Instructions is now deprecated.
But it is surely a backwards compatibility issue.

I have seen that if you specify a `maxFee` value and don't make use of the `maxFeeXRP` field in the constructor (like in the old days) you get random validation errors as the calculated fee is not properly formatted:

`[ValidationError(xrpToDrops: value '0.0064895625' has too many decimal places.)]`

**Comment by intelliot** [comment]
Good catch! I opened a PR which should fix this.

Alternatively, if we want the old behavior back, https://github.com/ripple/ripple-lib/pull/907 would do that.
