### ISSUE TITLE
Export createPaymentTransaction method

### ISSUE THREAD

**Issue by soichisumi** [ripple/ripple-lib#913]
I want to create transaction locally in a native environment (by caching fee, ledgerVersion and sequence).

But, because preparePayment function returns promise, my function using cannot be used in native environment.

Then I looked at the implementation of this function, and I found createPaymentTransaction is useful for creating txJSON sequentially.
Can ripple-lib export [createPaymentTransaction](https://github.com/ripple/ripple-lib/blob/develop/src/transaction/payment.ts#L79)?

**Comment by yoyoyousei** [comment]
In the meanwhile, I constructing txJSON lite:
```
const txJSON = {
    TransactionType: 'Payment',
    Account:          fromAddress,
    Destination:      toAddress,
    Amount:           amount,
    Flags:            2147483648,  // in Payment tx, 2147483648
    LastLedgerSequence: numMaxLedgerVersion,
    Fee:              fee,
    Sequence:         numSequence,
  }
```

**Comment by intelliot** [comment]
@yoyoyousei Why can't you use the promise returned by preparePayment?

Promises should work in native environments.

**Comment by yoyoyousei** [comment]
@intelliot I want to use ripple-lib in iOS app and JavascriptCore is used to call javascript functions.
But JavascriptCore seems not to handle promise-wrapped values.

**Comment by intelliot** [comment]
Changes needed on #922

**Comment by intelliot** [comment]
Closing this old issue, but anyone should feel free to re-open and/or create a new issue if the need arises. Thanks!
