### ISSUE TITLE
Can we create a gitter.im room for ripple-lib?

### ISSUE THREAD

**Issue by xefdan3ms** [ripple/ripple-lib#917]
Can we create a gitter.im room for ripple-lib? It could help build the community to have a place for veteran contributors and newcomers to discuss the ripple-liib project.

This would be created as a new room in the existing ripple community on gitter.im:
           https://gitter.im/ripple

So the room would be at this url:
           https://gitter.im/ripple/ripple-lib

**Comment by intelliot** [comment]
I think we can try this out. Thanks!
