### ISSUE TITLE
Improve Windows support

### ISSUE THREAD

**Issue by tpoti10188** [ripple/ripple-lib#938]
NPM Install - Failed at the ripple-lib@0.22.0 prepublish script.

[2018-08-25T14_09_44_739Z-debug.log](https://github.com/ripple/ripple-lib/files/2320769/2018-08-25T14_09_44_739Z-debug.log)

**Comment by intelliot** [comment]
Looks like you’re using Windows and ripple-lib 1.0.0-beta.5. I don’t have easy access to a Windows machine. Have you used ripple-lib before - did it work? 

I’m guessing there may be a windows compatibility problem.

**Comment by tpoti10188** [comment]
Last week on my work computer I used it on another computer that is also
windows 10 and it worked fine. I was able to build the file now problem.

I guess I could send a copy of the file from my other machine but didn't
realize it was only supported by Linux.

**Comment by intelliot** [comment]
@siegfriedschaefer Thanks! Would you like to open a PR?

**Comment by intelliot** [comment]
Closing this issue as stale, but feel free to re-open or create a new issue if the problem persists.
