### ISSUE TITLE
RippleAPI server should support unix socket

### ISSUE THREAD

**Issue by smsunarto** [ripple/ripple-lib#939]
ripple-lib seems to only work with `ws://` and `wss://`

It should support `ws+unix://` too.

**Comment by intelliot** [comment]
What is `ws+unix://` and how is it different from `ws://`?

**Comment by smsunarto** [comment]
@intelliot it's for websocket through unix socket 

ex: `ws+unix:///tmp/server.sock`

node.js `ws` library already supports it https://github.com/websockets/ws/blob/master/doc/ws.md so I think it would be sensical for ripple-lib to also support it by default.

**Comment by smsunarto** [comment]
@intelliot I've confirmed that ws+unix:// actually works out of the box with ripple-lib, you just need to update your regex validator here https://github.com/ripple/ripple-lib/blob/develop/src/common/schemas/input/api-options.json
