### ISSUE TITLE
When I try to send all the funds of one account it returns me an error

### ISSUE THREAD

**Issue by oscar-ordonez** [ripple/ripple-lib#942]
I am trying to send all the funds of a address to another. I tried subtracting the fee from the maxAmount, leaving the maxAmount with all the funds the account have and nothing. The error that's returning is: "resultCode":"tecUNFUNDED_PAYMENT","resultMessage":"Insufficient XRP balance to send."
 
Here is a part of my code:
`payment = {
            "source": {
                "address": balance.address,
                "maxAmount": {
                    "value": balance.value,
                    "currency": "XRP"
                }
            },
            "destination": {
                "address": address_to,
                "amount": {
                    "value": (balance.amount_sending - (fee / balances.length)).toString(),
                    "currency": "XRP"
                }
            }
        };
        instructions = {
                "fee": fee.toString(),
                // sequence of all transactions starting in 1
                "sequence": balance.sequence,
                "maxLedgerVersion": null
        };`

**Comment by tuloski** [comment]
https://developers.ripple.com/reserves.html

**Comment by oscar-ordonez** [comment]
Thank you!
