### ISSUE TITLE
sign transaction gives tefBAD_AUTH_MASTER(Auth for unclaimed account needs correct master key)

### ISSUE THREAD

**Issue by aniketdivekar** [ripple/ripple-lib#956]
I'm trying to sign below transaction on Testnet using the [ripple-lib](https://github.com/ripple/ripple-lib)
```
{
  "Account": "rfwG2i1UdTSThLTTXL115gUtxaJjPivy3R",
  "Amount": "21750000",
  "Destination": "rhTCs58WSRzVM5aqRSaakvx3y5FZHe3EAo",
  "DestinationTag": 568562286,
  "Fee": "10",
  "LastLedgerSequence": 13484077,
  "Sequence": 1,
  "TransactionType": "Payment"
}
```
I created the account on [Testnet](https://developers.ripple.com/xrp-test-net-faucet.html) as suggested in one of the comments in https://github.com/ripple/ripple-lib/issues/937 and using the secret provided there to sign the transaction. But I'm getting this error

```
{
  "result": {
    "engine_result": "tefBAD_AUTH_MASTER",
    "engine_result_code": -183,
    "engine_result_message": "Auth for unclaimed account needs correct master key.",
    "status": "success",
    "tx_blob": "*****",
    "tx_json": {
      "Account": "rfwG2i1UdTSThLTTXL115gUtxaJjPivy3R",
      "Amount": "21750000",
      "Destination": "rhTCs58WSRzVM5aqRSaakvx3y5FZHe3EAo",
      "DestinationTag": 568562286,
      "Fee": "10",
      "LastLedgerSequence": 13484077,
      "Sequence": 1,
      "SigningPubKey": "*******",
      "TransactionType": "Payment",
      "TxnSignature": "********",
      "hash": "4DBA0281DF4FAD19DED50EAD991A02CEC86B3F7D96227D77D06678CA8755EE46"
    }
  }
}
```

How do I fix this issue? Am I missing anything?
I'm using correct `account` and `secret` as provided on generating address on Testnet. 
Any help is much appreciated. Thanks in advance.

**Comment by aniketdivekar** [comment]
Never mind. I just made a blunder.

**Comment by intelliot** [comment]
Thanks for following up and closing the issue. For the benefit of those who get a similar error in the future, what was the blunder? Was it just the wrong secret?

**Comment by aniketdivekar** [comment]
The secret was correct. I just needed to restart my server(which I thought I had already done) to load the new secret from k8s secrets. And hence the blunder. 😓
