### ISSUE TITLE
Allow to remove signerList

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#971]
See https://github.com/ripple/ripple-lib/pull/950

**Comment by Likwidt** [comment]
Are issues like this still worth fixing?

**Comment by intelliot** [comment]
@Likwidt Sure, we would welcome a PR. It's a good example of how to use the `rippled` transaction format. On the other hand, preparing the transaction in `rippled` format directly and using ripple-lib's `prepareTransaction` method is also a good workaround.
