### ISSUE TITLE
instance.server does not match pattern "^(wss?|wss?\\+unix)://

### ISSUE THREAD

**Issue by Navjeetkumar123** [ripple/ripple-lib#973]
I am trying to call get-account info api from cmd.
Running the command : ./node_modules/.bin/babel-node get-account-info.js
Node modules and get-account-info.js are in same directory.
Refering the ripple api link:  https://developers.ripple.com/get-started-with-rippleapi-for-javascript.html

The error i am getting:
/opt/ripple-dev-portal/node_modules/ripple-lib/dist/npm/common/schema-validator.js:157
        throw new errors_1.ValidationError(result.errors.join());
        ^
[ValidationError(instance.server does not match pattern "^(wss?|wss?\\+unix)://")]
    at Object.schemaValidate (/opt/ripple-dev-portal/node_modules/ripple-lib/src/common/schema-validator.ts:157:11)
    at apply (/opt/ripple-dev-portal/node_modules/lodash/lodash.js:475:27)
    at Object.wrapper [as apiOptions] (/opt/ripple-dev-portal/node_modules/lodash/lodash.js:5323:16)
    at new RippleAPI (/opt/ripple-dev-portal/node_modules/ripple-lib/src/api.ts:119:14)
    at Object.<anonymous> (/opt/ripple-dev-portal/get-account-info.js:6:13)
    at Module._compile (module.js:643:30)
    at loader (/opt/ripple-dev-portal/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/ripple-dev-portal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

Please help!! Thanks in advance

**Comment by intelliot** [comment]
@Navjeetkumar123 Could we see `get-account-info.js`?

Here's an example of how it should look:
```javascript
const api = new RippleAPI({
  server: 'wss://s1.ripple.com' // Public rippled server
});
```

**Comment by Navjeetkumar123** [comment]
This is the code for get -account-info:

'use strict';
const RippleAPI = require('ripple-lib').RippleAPI;

const api = new RippleAPI({
  server: 'wss://s1.ripple.com' // Public rippled server
});
api.connect().then(() => {
  /* begin custom code ------------------------------------ */
  const myAddress = 'rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn';

  console.log('getting account info for', myAddress);
  return api.getAccountInfo(myAddress);

}).then(info => {
  console.log(info);
  console.log('getAccountInfo done');

  /* end custom code -------------------------------------- */
}).then(() => {
  return api.disconnect();
}).then(() => {
  console.log('done and disconnected.');
}).catch(console.error);

**Comment by intelliot** [comment]
@Navjeetkumar123 I copy and pasted your code and it works fine for me. How did you encounter the error?

Output:
```
% node get-account-info.js 
getting account info for rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn
{ sequence: 375,
  xrpBalance: '396.015188',
  ownerCount: 9,
  previousInitiatedTransactionID:
   '4F17A26A67D237781C8BD480D23FA0C489B10B89CAE20B3804723852AAA1FDBE',
  previousAffectingTransactionID:
   '4D8F33648EB0EDE30FEE6041BDD3135A4F6CBF9D5302A8BCA711BFD08E96AE6B',
  previousAffectingTransactionLedgerVersion: 38203698 }
getAccountInfo done
done and disconnected.
```

**Comment by Navjeetkumar123** [comment]
Yes even it worked on mine pc also. I was trying to run it in corporate proxy..so DNS was failing.
Anyways..Thanks for your time @intelliot

**Comment by intelliot** [comment]
Glad you figured it out!
