### ISSUE TITLE
Is bignumber.js really necessary?

### ISSUE THREAD

**Issue by r0bertz** [ripple/ripple-lib#982]
The biggest number ripple-lib can deal with, IIUIC, should be the number of drops: 100000000000000000.

This is less than Number.MAX_VALUE.

Can anyone help me to understand the decision to use bignumber.js? 

Thanks in advance!

**Comment by tuloski** [comment]
There are also IOUs, which can be a number bigger that XRP drops.
And maybe there are also other motivations.

**Comment by FredKSchott** [comment]
Basically, because JavaScript:

```
> .2 + .1
0.30000000000000004
```

If you mean why `bignumber.js` vs. one of the other math libraries, fair point. I know `big.js` is about half the size and may contain everything that we need.

**Comment by r0bertz** [comment]
Thanks! I guess that must be it. I am new to JavaScript.

**Comment by FredKSchott** [comment]
np! Thanks for the question! It's easy to add dependencies without really considering their value / cost.
