### ISSUE TITLE
Getting Insufficient XRP balance when I am transferring XRP even though my wallet has more than 20XRP

### ISSUE THREAD

**Issue by anubnair** [ripple/ripple-lib#983]
I understand that we need to keep minimum 20XRP in wallet and we cant transfer that amount to another account. My ripple testnet account(rLhQVp2m371Z9h64atp8qjPcKPTgSnqiAh) have 40XRP and trying to transfer 1XRP and getting "Insufficient XRP balance to send" error! I understand that 20XRP need to keep in a wallet. So I did an experiment, as per my experiment from any account, we can not withdraw more than 40XRP. I am doing a multisigned transaction.

**Comment by tuloski** [comment]
As explained here> https://developers.ripple.com/signerlist.html#signerlists-and-reserves, you probably have 2 signers in the multi-sig. The signer list takes 2 more reserves (i.e. 5XRP x 2) and each account one more reserve (5XRP x 2), for a total of 20 + 10 +10 = 40 XRP.

**Comment by intelliot** [comment]
@tuloski is correct. Here's a small script that shows that your account owns 4 objects. With the current Owner Reserve of 5 XRP, your account's reserve is 40 XRP.

```
const RippleAPI = require('ripple-lib').RippleAPI
const api = new RippleAPI({server: 'wss://s.altnet.rippletest.net:51233'})

const address = 'rLhQVp2m371Z9h64atp8qjPcKPTgSnqiAh'

getReserve(address)

async function getReserve(address) {
  await api.connect()
  const accountInfo = await api.getAccountInfo(address)
  const ownerCount = accountInfo.ownerCount
  console.log('Objects owned:', ownerCount)
}
```
