### ISSUE TITLE
prepareTransaction should not overwrite `Fee`

### ISSUE THREAD

**Issue by mDuo13** [ripple/ripple-lib#997]
Similar to #990, the prepareTransaction() method should respect the `Fee` parameter of the input txJSON if provided.

Example:
```js
  const resp = await api.prepareTransaction({
    "TransactionType": "AccountSet",
    "Account": from_address,
    "Fee": "10"
  }) // No-op tx
  console.log("resp:", resp)
```

Output:

```js
resp: { txJSON:
   '{"TransactionType":"AccountSet","Account":"rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn","Fee":"12","Flags":2147483648,"LastLedgerSequence":46447424,"Sequence":376}',
  instructions:
   { fee: '0.000012', sequence: 376, maxLedgerVersion: 46447424 } }
```

Note that the `Fee` is `"12"` , not `"10"` as specified.

**Comment by mDuo13** [comment]
Incidentally, I think the prepareSettings() function doesn't support sending a [nop transaction](https://developers.ripple.com/cancel-or-skip-a-transaction.html) like this.

**Comment by intelliot** [comment]
Great catches - thanks!

Note that the workaround for now is to give prepareTransaction the third parameter, the `instructions` object, where you indicate the `fee` and other instructions.
